### ISSUE TITLE
List Feed - Fails (CIRCL OSINT Feed)

### ISSUE THREAD

**Issue by gra55h0pp3r** [MISP/MISP#1489]
The list feed for The Botvrij.eu Data successfully completes, but when I try to download the feeds from CIRCL OSINT Feed it fails. It looks like a couple of the feeds were added, but it failes to completely download all 400+ events within the feed.

**Comment by gra55h0pp3r** [comment]
Still no clue as to why it's still fails after downloading 33 events. If I go into the feed an manually download an event it downloads without any issues, so is it crashing on one event possibly?

**Comment by iglocska** [comment]
That is indeed weird. Looking into it.

**Comment by iglocska** [comment]
Could you check if the Job reports any errors? You can do this by navigating to Administration -> Jobs and it should show a failed job (under the default worker tab). You can click on the magnifying glass to view the stack trace.

**Comment by gra55h0pp3r** [comment]
I tried clicking on the magnify glass, but nothing happens.

**Comment by gra55h0pp3r** [comment]
So I think I finally figured out which JSON file is the culprit that is causing the application to fail. I did a simple wget of all the JSON files and every time it would crash on 57469dce-e55c-4edc-8e0b-43a6950d210f.json. I see the file is over 47MB and that's a large file. Who can remove that file or change it so it's not as large and not causing the list to fail.

Filename: 57469dce-e55c-4edc-8e0b-43a6950d210f.json (47MB)
Info: Malspam 2016-05-26 - Locky - samples reversed, xored (0x73 or 0x1c); samples reversed + long xor key

**Comment by adulau** [comment]
Maybe you have reach the limit of the PHP memory configuration? Could you check your php.ini file and how much is specified at memory_limit? We recommend to increase significantly the default value.

**Comment by gra55h0pp3r** [comment]
Okay I modified the memory_limit and upload_max_filesize and restarted the rh-php56 service, but now I get the following error:

Failed at: Thu Sep 01 08:05:35 EDT 2016
Exception: Resque_Job_DirtyExitException
Error: Job exited with exit code 255
(Click to hide stack trace)
#0 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(109): Resque_Worker->work('5')
#1 /var/www/MISP/app/Vendor/kamisama/php-resque-ex/bin/resque(100): startWorker('default', 1, Object(MonologInit\MonologInit), '5')
#2 {main}

I'm also noticed the snort export isn't exporting any of the signatures that are identified as NIDS. Everytime I generate and export it's blank?

**Comment by iglocska** [comment]
For the NIDS, it was indeed a freshly introduced bug, if you git pull it should be resolved. The Resque error is new, not sure what's causing it yet.

**Comment by gra55h0pp3r** [comment]
I ran a 'git pull origin 2.4' and it's still not working. I restarted the workers, but still not working. I checked the NidsExport.php file and I see the changes are in the file.

**Comment by gra55h0pp3r** [comment]
I did a hard reset on the server and it's working now. Was there something other than restarting the redis service and workers that I should have also restarted?

**Comment by iglocska** [comment]
Apache for the memory setting changes, but other then that you generally don't have to restart anything. It's puzzling for sure. So the Suricata/Snort export is fixed? I am testing it on my end but it seems to work correctly now.

**Comment by gra55h0pp3r** [comment]
Yes, it's working on my end again. I was wondering why it stopped, because I used it on a previously build. Good to see the issue has been fixed and now we can start export snort rules again. :-)

I'm working on the next issue at hand which is misp-modules. I submitted another issue about installing on CENTOS 7.

**Comment by iglocska** [comment]
Ah I see. Interesting, we generally use Ubuntu but let's see if some of the CentOS users can chip in with ideas :) If all else fails I'll give it a bash over the weekend and write down some documentation for the installation.
