### ISSUE TITLE
Error: Class 'CakeObject' not found

### ISSUE THREAD

**Issue by Gudmo** [MISP/MISP#2094]
Since upgrading to MISP 2.4.69 my feeds have stopped working. I get this Cakeobject error in my logs but I have not found any solution to this.  I tried upgrading to 2.4.70 but still nothing.

I'm on cake version 2.9.6

2017-03-28 11:29:52 Error: [SocketException] stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://misp:443 (Unknown error)
Request URL: /servers/previewIndex/2
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/CakeSocket.php(347): CakeSocket->connect()
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(377): CakeSocket->write('GET /events/ind...')
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Network/Http/HttpSocket.php(466): HttpSocket->request(Array)
#3 /var/www/MISP/app/Model/Server.php(3250): HttpSocket->get('https://misp.op...', '', Array)
#4 /var/www/MISP/app/Controller/ServersController.php(83): Server->previewIndex('2', Array, Array)
#5 [internal function]: ServersController->previewIndex('2')
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(ServersController), Array)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(ServersController), Object(CakeRequest))
#9 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2017-03-28 11:29:52 Error: Fatal Error (256): [CakeException] Unknown status code
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(228): CakeResponse->statusCode(2)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Error/ExceptionRenderer.php(190): ExceptionRenderer->error400(Object(SocketException))
#2 /usr/share/php/Cake/Error/ErrorHandler.php(127): ExceptionRenderer->render()
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main} in [/usr/share/php/Cake/Error/ErrorHandler.php, line 138]
2017-03-28 11:29:52 Error: Fatal Error (1): Uncaught InternalErrorException: Internal Server Error in /usr/share/php/Cake/Error/ErrorHandler.php:276
Stack trace:
#0 /usr/share/php/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(256, '[CakeException]...', '/usr/share/php/...', 138)
#1 [internal function]: ErrorHandler::handleError(256, '[CakeException]...', '/usr/share/php/...', 138, Array)
#2 /usr/share/php/Cake/Error/ErrorHandler.php(138): trigger_error('[CakeException]...', 256)
#3 [internal function]: ErrorHandler::handleException(Object(SocketException))
#4 {main}
  thrown in [/usr/share/php/Cake/Error/ErrorHandler.php, line 276]
2017-03-28 11:29:52 Error: [InternalErrorException] Internal Server Error
Request URL: /servers/previewIndex/2
Stack Trace:
#0 /usr/share/php/Cake/Error/ErrorHandler.php(213): ErrorHandler::handleFatalError(1, 'Uncaught Intern...', '/usr/share/php/...', 276)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(970): ErrorHandler::handleError(1, 'Uncaught Intern...', '/usr/share/php/...', 276, Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/App.php(943): App::_checkFatalError()
#3 [internal function]: App::shutdown()
#4 {main}
2017-03-28 11:31:24 Error: Class 'CakeObject' not found in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 31]

**Comment by iglocska** [comment]
Could you git pull and restart all backround workers? This bug should be resolved in the latest version.

If you are already running the latest version already, just restart all workers from the server settings -> workers interface.

**Comment by Gudmo** [comment]
I removed cakephp and did a full git pull, reinstalled basicly... the error is still there

I'm on Ubuntu 16.04

**Comment by iglocska** [comment]
It's not directly a cakephp issue, it's a cakeresque issue with existing workers. Restarting the workers should fix it!

**Comment by Gudmo** [comment]
The machine has been rebooted, the workers have been restarted. Multiple times.. Trust me it hasn't fixed the issue :(

**Comment by iglocska** [comment]
Hmm, ok that is weird indeed.

**Comment by iglocska** [comment]
Just to reiterate, you still get the cakeobject erros, not what's in the actual stack traces above, right?

**Comment by adulau** [comment]
Maybe there is multiple issues. Regarding the TLS connectivity, could you try to connect using "openssl s_client"? As the certificate validation failed.

~~~~
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://misp:443 (Unknown error)
~~~~

**Comment by Gudmo** [comment]
yes, I get cakeobject errors aside from the stack traces

**Comment by Gudmo** [comment]
Today, after running self update, update certs and validate on the composer and restarting everything I no longer see the stacktrace errors. Only these errors when trying to pull any feed or server.

$ cat error.log
2017-03-29 08:34:58 Error: Class 'CakeObject' not found in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 31]

$ cat resque-worker-error.log
PHP Fatal error:  Class 'CakeObject' not found in /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php on line 31
Fatal Error Error: Class 'CakeObject' not found in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php, line 31]

No feeds are working.. Anyone know of a better way to debug this?

**Comment by Gudmo** [comment]
Going back through the logs I can see these CakeObject errors starting after upgrading from 2.5.68 to 2.5.69 on the 11th of March. So the error is introduced with version 2.4.69

**Comment by Gudmo** [comment]
So I downgraded to the 2.4.67 branch but nothing changed
Next I checked composer but decided to downgrade cake-resque first. 
After downgrading to cake-resque 4.1.1 from 4.1.2 the issue seems to be resolved.

**Comment by Gudmo** [comment]
Just to make sure I upgraded to MISP 2.4.70 and the error came back, so I'm back to 2.4.67 and cake-resque at 4.1.1 which seems to be the combo that works for me. Let me know if you want me to test this further if you'd like debugging info.

**Comment by RichieB2B** [comment]
cake-resque 4.1.2 and 4.1.1 only differ in debug handling. It should not make any difference for this issue. I have also seen these error early March, but I haven't seen them the last few weeks though.

**Comment by iglocska** [comment]
Yeah it's weird that it persists. For us it went away after restarting the
workers.

**Comment by cgi1** [comment]
Had the same issue. Removing a (manually?) installed version of `cakephp` using `aptitude purge cakephp` fixed the problem.

**Comment by iglocska** [comment]
Woah that is good to know! We didn't have to do that after the update, but seems like there are a few that are stuck on this issue - will add that to the FAQ.

Thanks for the heads-up!

**Comment by dewiestr** [comment]
Restarting the workers did in fact help for me.

**Comment by Gudmo** [comment]
As an update
I upgraded to 2.4.80 now and hit the same issue

The Solution 

> aptitude purge cakephp

Worked for me - Restarting the workes did not

**Comment by iglocska** [comment]
Odd, normally you don't have cakephp installed under apt.
