### ISSUE TITLE
MISP objects GUI issue file object editing

### ISSUE THREAD

**Issue by c-goes** [MISP/MISP#2528]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug 
| OS version (server)       | Ubuntu xenial
| OS version (client)       | 10
| PHP version               | 7.0
| MISP version / git hash   | 2.4.80
| Browser                   | If applicable

### Expected behavior

malware-sample field should not be empty or overwritten on submit if file object is being changed

### Actual behavior

malware-sample field of file object is not there any more in the gui. another upload of the same file fails.

### Steps to reproduce the behavior

- Add a file object with filename
- Edit this file object again
- field malware sample is now empty
- change an attribute like filename
- submit the form
- malware sample attribute of file object is now missing
- another try to upload the file causes an error

**Comment by c-goes** [comment]
Workaround: This bug doesn't happen when PyMISP API is used instead because the attachment is not in the search output of pymisp.search()

To add another filename to a file object one could use


```python
def find_objects(obj_type, obj_relation, value, event_id=None) -> list:
    search = pymisp.search('events', values=value, eventid=str(int(event_id))) \
        if event_id else pymisp.search('events', values=value)

    resp = search['response']
    if resp:
        # events
        events = list(map(lambda x: x['Event'], resp))

        # objects of the events
        objs = list(map(lambda x: x['Object'], events))[0]

        # object name matches
        objs_name_match = list(filter(lambda x:
                                      x['name'] == obj_type and
                                      x['deleted'] is False,
                                      objs))

        obj_list = list(filter(lambda x: any(
            y['value'] == value and y['object_relation'] == obj_relation and y['deleted'] is False
            for y in x['Attribute']
        ), objs_name_match))

        if not obj_list:
            return []
        else:
            return obj_list
    else:
        return []

def submit_updated_object(obj_dict, updater_func=lambda x: x) -> MISPObject:
    obj_type = obj_dict['name']

    try:
        template_id = [x['ObjectTemplate']['id'] for x in pymisp.get_object_templates_list() if
                       x['ObjectTemplate']['name'] == obj_type][0]
    except IndexError:
        valid_types = ", ".join([x['ObjectTemplate']['name'] for x in pymisp.get_object_templates_list()])
        print("Template for type %s not found! Valid types are: %s" % (obj_type, valid_types))
        exit(1)
    else:
        misp_object = GenericObjectGenerator(obj_type)
        misp_object.from_dict(**obj_dict)
        setattr(misp_object, "distribution", obj_dict['distribution'])
        attrs = []
        for attribute in obj_dict['Attribute']:
            a = MISPObjectAttribute({})
            a.from_dict(**attribute)
            attrs.append(a)
        misp_object['Attribute'] = attrs
        updater_func(misp_object)
        pymisp.add_object(obj_dict['event_id'], template_id, misp_object)
        return misp_object



search_obj = find_objects("file", "sha256", sha256_hash, event_id=event_id)

if len(search_obj) > 0:
    search_obj = search_obj[-1]
    filename_attrs = list(filter(lambda x: x['object_relation'] == 'filename', search_obj['Attribute']))
    filenames = list(map(lambda x: x['value'], filename_attrs))
    dist = list(map(lambda x: x['distribution'], filename_attrs))[-1]
    new_filename = os.path.basename(path)
    if new_filename not in filenames:
        updater_func = lambda x: x.add_attribute(object_relation="filename", value=new_filename,
                                                 distribution=dist)
        submit_updated_object(search_obj, updater_func=updater_func)
```

**Comment by adulau** [comment]
It should be fixed in recent version. Could you test? and reopen if this is still the case. Thank you very much!

**Comment by c-goes** [comment]
I tested with today's version. Problem is still there.
When editing the file object, next to the "browse" button it states "No file selected".
After saving, the sample attribute is not there any more.

No rights to reopen.
