### ISSUE TITLE
Add user option to have no confirmation when deleting attributes

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#298]
Add user option to have no confirmation when deleting attributes if they so choose.
Default value like now: with confirmation

**Comment by Rafiot** [comment]
Fixed.

**Comment by elhoim** [comment]
Not fixed. At least not up to 2.4 hotfix 124.
But we can decide to not implement it.

**Comment by Rafiot** [comment]
oh, sorry, I add is back on milestone 2.5 and we decide at the time.
