### ISSUE TITLE
In add attribute, allow to quickly add another attribute

### ISSUE THREAD

**Issue by elhoim** [MISP/MISP#299]
In the ajax popup to add attribute add a checkbox to return to the same popup to add another attribute after the first one has been added.

**Comment by Rafiot** [comment]
Fixed, right?

**Comment by iglocska** [comment]
This is still not implemented and it's kind of on the back-burner.

**Comment by Rafiot** [comment]
Ok, feel free to move the milestones around if needed, I just wanted to make sure we stop having >200 issues with plenty of duplicates and half of them more or less fixed :)

**Comment by Rafiot** [comment]
Use the freetext import.
