### ISSUE TITLE
Sharing group extension doesn't work

### ISSUE THREAD

**Issue by rommelfs** [MISP/MISP#3255]
> When I try to edit the a sharing group on MISP instance,
> I get an "Action not allowed"-error and that "The requested address
> '/SharingGroups/edit/22' was not found on this server". It
> seems to me that I should have the rights to edit the group.

**Comment by rommelfs** [comment]
Tried to reproduce the issue with two orgs being part of a sharing group. Created by org A, extend rights for org B.
Org B tries with OrgAdmin role to modify the sharing group. Worked without a problem.

**Comment by iglocska** [comment]
Fixed, indeed this could happen with one of the two ways of editing the sharing group. The issue was an inconsistency with the controller name in underscored vs camel-case format throwing the ACL off and blocking you for no reason.

**Comment by torri019** [comment]
It seems the issue still exist. I am OrgAdmin, trying to extend a sharing group (Global Actions -> List Sharing Groups -> Edit) and still getting the same "Action not allowed" error. Manually changing the URL from camel-case to underscore does also not solve the issue.

**Comment by iglocska** [comment]
It works for me, which version are you on?

**Comment by torri019** [comment]
I am using CIRCL MISP.

**Comment by iglocska** [comment]
Which sharing group ID are you trying to edit? Just the local ID please ;)

**Comment by iglocska** [comment]
or even better, could you send me a mail with your user ID and the sharing group ID? andras[at]circl.lu

**Comment by torri019** [comment]
My Id is 170, sharing group ID 22.

**Comment by iglocska** [comment]
This should be fixed now, thanks for the heads-up!

**Comment by torri019** [comment]
Works perfectly now, thanks!

**Comment by iglocska** [comment]
Thanks for the feedback!
