### ISSUE TITLE
Notice: Undefined variable: uuid in [/var/www/MISP/app/Model/Feed.php, line 450] Notice Error: Undefined variable: uuid in [/var/www/MISP/app/Model/Feed.php, line 448]

### ISSUE THREAD

**Issue by HachimanSec** [MISP/MISP#3366]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Linux ecs-6c50 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
| MISP version / git hash   | v2.4.92 (6eb4e49f2c62d05e671e3482ac1b21004ce58ee3)	
| Browser                   | Mozilla

### Actual behavior
Every time I restart the apache server, I receive error in regards to Feed.php

### Steps to reproduce the behavior
```
restart apache2 server
cat /var/www/MISP/app/tmp/logs/resque-worker-error.log
Notice: Undefined variable: uuid in [/var/www/MISP/app/Model/Feed.php, line 450]
Notice Error: Undefined variable: uuid in [/var/www/MISP/app/Model/Feed.php, line 448]
Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 992]
Warning Error: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 992]

cat /var/www/MISP/app/tmp/logs/error.log
2018-06-21 15:10:02 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 776]
```

**Comment by adulau** [comment]
`Warning: mkdir(): Permission denied in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/Folder.php, line 582]`

It seems that you might have some permission issues on the server. Could you rerun your permission part of the installation script?

**Comment by HachimanSec** [comment]
The permission issue is a leftover from the installation. I reran the permission part and restarted the service, the foreach() issue remains. However the permission denied error is gone. 

`2018-06-21 19:57:30 Warning: Invalid argument supplied for foreach() in [/var/www/MISP/app/Model/Feed.php, line 1018]
`

**Comment by amartinr** [comment]
Hi,

I'm experiencing the same warning with v2.4.93 in CentOS 7. The error shows up while fetching feeds via a scheduled jobs at 1:00.
```
2018-06-28 01:00:50 Notice: Undefined variable: uuid in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 448]
Notice Error: Undefined variable: uuid in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 450]

2018-06-28 01:00:50 Notice: Undefined variable: uuid in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 450]
Notice Error: Undefined variable: uuid in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 448]
```

It also happens for lines 776 and 992 in `app/Model/Feed.php`.

```2018-06-29 01:02:28 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 776]
Warning Error: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 776]

2018-06-29 01:02:38 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 776]
Warning Error: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 992]
```
In the Feeds page some entries have _Error: Invalid event!_. Some others show _New fixed event_.

**Comment by SteveClement** [comment]
@TomHubGit @amartinr is this still an issue with the latest version?

**Comment by iglocska** [comment]
Should be fixed now, thanks for the report.

**Comment by amartinr** [comment]
Sorry for not having answered before. I was absent from office all this time. The _Undefined variable: uuid_ error is gone, thank you.

We're still experiencing the following warnings, which result on feeds not being fetched.
```
2018-07-29 00:03:52 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 777]
2018-07-29 00:04:01 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 777]
2018-07-29 07:00:21 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 993]
2018-07-29 07:01:20 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 993]
2018-07-30 00:04:16 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 777]
2018-07-30 00:04:26 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 777]
2018-07-30 07:00:18 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 993]
2018-07-30 07:00:44 Warning: Invalid argument supplied for foreach() in [/opt/rh/httpd24/root/var/www/html/MISP/app/Model/Feed.php, line 993]
```
It seems that this only happen with non-MISP feeds. We just disabled the feeds showing the message _Error: Invalid event!_ on the web interface.

Anyway, we'd open a different issue to deal with this warning.

**Comment by iglocska** [comment]
Which commit ID are you on exactly? Feed.php must have been updated already as those lines don't correspond to the error messages, could you fetch the latest version and try again? Thanks!

**Comment by HachimanSec** [comment]
Hi @SteveClement , thanks for your patience. The update went unnoticed on my side. I have to reinstall my MISP instance anyway. Lets see how this will work.

Anyway, thank you so far for your support!

**Comment by amartinr** [comment]
Hi @iglocska, thanks so much for your interest. We're at a6b8a4a. Obviously we are way behind the current state of 2.4 branch. 

Unfortunately we don't have time now to update our MISP instance. I'll update it as soon as I can. Do you recommend updating to b65dce3 or any other commit in particular in order to test again?
