### ISSUE TITLE
Bug: datefrom ignored in PyMISP request

### ISSUE THREAD

**Issue by fregoetel** [MISP/MISP#3855]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | macOS / pyMISP
| PHP version               | 7.2
| MISP version / git hash   | 2.4.96
| Browser                   | PyMISP access (no browser)

### Expected behavior
If `datefrom` parameter is set to a datetime one hour ago in the PyMISP api, only events which are not older than one hour are selected

### Actual behavior
`Datefrom` parameter has no effect. All events are selected, no matter what is in the variable `datefrom`

### Steps to reproduce the behavior
```
misp_instance = pymisp.api.PyMISP(url=misp_url, key=misp_key, ssl=misp_verifycert, out_type='json',
                                  debug=None, proxies=None, cert=None, asynch=False)
events = misp_instance.search_index(datefrom=(datetime.datetime.now() - datetime.timedelta(hours=1)))
```

### Logs, screenshots, configuration dump, ...
<img width="1192" alt="bildschirmfoto 2018-11-08 um 13 31 15" src="https://user-images.githubusercontent.com/44868688/48199933-ee0b9400-e35d-11e8-82f6-aca4618d326a.png">
<img width="816" alt="bildschirmfoto 2018-11-08 um 13 31 26" src="https://user-images.githubusercontent.com/44868688/48199979-04b1eb00-e35e-11e8-978f-ec25a8e3358c.png">

**Comment by adulau** [comment]
Indeed, it works at the RestSearch API level but it doesn't work on index search level (MISP 2.4.97 HEAD).

**Comment by Rafiot** [comment]
So two things : 
1. There was a bug in PyMISP, it is now fixed: https://github.com/MISP/PyMISP/commit/a92e2a2d432e06a6f3dc223722e7149a373c1486
2. Date from/to is the date set by the user when creating the event. I guess you want to use timestamp instead, which is based on the last update on the event.

**Comment by WaryWolf** [comment]
I think this was caused by b4f084f9fe66547d65bb1d9187aa56bd8c9b2dc3 - we're seeing the same issue here.

With some help, we tracked down the issue, in EventsController.php: 

https://github.com/MISP/MISP/blob/caa5d82462d758ba7f0c48472dec21ad0230eee4/app/Controller/EventsController.php#L276-L303

It looks like there's case-insensitivity employed in the code with the strtolower() call on line 301, but before that happens, each filter gets compared against the overrideAbleParams array and 'search' gets prepended to the key. This happens before any lowercasing, so the "Datefrom" and "Dateuntil" filters won't match.

I'm adding "Datefrom" and "Dateuntil" back into the overrideAbleParams array until there's a cleaner solution. It looks like the latest PyMISP has a fix for this but anyone using an older version is getting unfiltered results at the moment.

**Comment by fregoetel** [comment]
It's still not working with MISP 2.4.98 and PyMISP 2.4.96.
The issue does not occur on my MISP 2.4.95 machine.

**Comment by fregoetel** [comment]
Now for MISP 2.4.99 datefrom in search_index() is working again, but the date_from parameter in search() is not working anymore. There seems to be a correlation

**Comment by github-germ** [comment]
perhaps this is related to my issue in https://github.com/MISP/PyMISP/issues/308 ??

**Comment by WaryWolf** [comment]
Hi, is there any chance that my PR above could be looked at and merged? we've been applying the fix manually after updating each time since late november last year, because this bug causes all of our API users to receive non-date-filtered results otherwise.

Thanks for your time.

**Comment by iglocska** [comment]
Just pushed a somewhat hacky fix that should solve it by just lower casing all incoming search parameters, should work. Completely missed this one.
