### ISSUE TITLE
STIX2 export is broken

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP#3999]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 9.6
| PHP version               | 7.0
| MISP version / git hash   | 2.4, b253303edc0e18594ffe380503b28e7e55cc9b6f
| Browser                   | Firefox

### Expected behavior
Stix2 export should create a stix2 file when the "Generate" button is pressed

### Actual behavior
Stix2 export creates an empty file

### Steps to reproduce the behavior
Go to
Event Actions -> Export -> press "Generate" button in the Stix2 row

### Logs, screenshots, configuration dump, ...
Log output of the error:

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1213, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1210, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 56, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 56, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 119, in handler
    i = self.__set_identity()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 98, in __set_identity
    identity_class="organization", interoperability=True)
  File "/var/www/MISP/venv/lib/python3.5/site-packages/stix2/base.py", line 142, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).

**Comment by adulau** [comment]
You have the old version of the STIX library, you can update by doing the following (assuming your MISP is installed in /var/www/MISP).

`cd /var/www/MISP`
`git pull origin 2.4`
`git submodule sync`
`git submodule update`
`cd cti-python-stix2/`
`/var/www/MISP/venv/bin/pip install .`

**Comment by worldopener** [comment]
everything was up to date

I followed the debian documentation but it just mentions this part about stix2

# install STIX2.0 library to support STIX 2.0 export:
sudo -u www-data ${PATH_TO_MISP}/venv/bin/pip install stix2

i now also did a 

cd cti-python-stix2/
/var/www/MISP/venv/bin/pip install .

but i still get the new error

Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1213, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1210, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 56, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 56, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 158, in handler
    report = self.eventReport()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 70, in eventReport
    source += " - {}".format(attribute['comment'])
NameError: name 'attribute' is not defined

**Comment by chrisr3d** [comment]
Thank you for reporting this issue, it was a wrong variable name I missed.
It is now fixed with the latest version

**Comment by worldopener** [comment]
Still doesn't work here, now i get:

```
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1263, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1260, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 176, in handler
    report = self.eventReport()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 80, in eventReport
    markings.append(self.markings[tag_name]['id'] if tag_name in self.markings else self.create_marking(tag_name))
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 670, in create_marking
    _type, value = tag.split(':')
ValueError: too many values to unpack (expected 2)
```

If the command is needed to get a working stix2 export

```
cd cti-python-stix2/
/var/www/MISP/venv/bin/pip install .
```

someone should update the documentation of debian maybe for other distros too to get a working stix2 export

**Comment by worldopener** [comment]
thanks the latest commit https://github.com/MISP/MISP/commit/70c2dff5959dc7b42768c526134cd06afe238118 fixed the error and now it's possible to create stix2 exports.

Thank you very much

**Comment by chrisr3d** [comment]
Indeed I was updating the part of the code where you got the issue, sorry for the inconvenience. Glad to see it is working for you now.

I also updated the documentation

Thank you for reporting your issues, do not hesitate to ping us again if anything goes wrong
