### ISSUE TITLE
Unable to export bro format

### ISSUE THREAD

**Issue by jdeluzio** [MISP/MISP#4050]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug, Question, support...
| OS version (server)       | Ubuntu 18.04.1
| OS version (client)       | XP, Seven, 10, Ubuntu, ...
| PHP version               | 7.2.10-0ubuntu0.18.04.1
| MISP version / git hash   | 2.4.101 autogenerated VM

### Expected behavior
Export events in bro format

### Actual behavior
I have tried both creating a simple event as domain, ids and publishing it as well as pulling in various feeds.  In every case I'm able to generate every format other than bro.  When I attempt to generate for bro the process field shows Adding but a refresh immediatly goes back to N/A.  

For the job it shows cache_bro, Fetching events Status - Failed, Progress - Queued.  I've verified that all workers are healthy and that the VM is up to date.  I've tried with several different versions of the VM over the last few weeks and I always see the exact same behavior. 

The version I'm testing today is MISP_v2.4.101@cb41b4db38a06fde0fc6c4d80e937b1599da3842.ova

### Steps to reproduce the behavior
Load the VM and attempt to export in bro format.

### Logs, screenshots, configuration dump, ...
This is a base config from the VM using the admin@admin.temp login.

**Comment by befrankt** [comment]
jdeluzio, did you even run into a fix? I am seeing exactly the same issue within the same environment but with MISP 2.4.99

**Comment by jdeluzio** [comment]
@befrankt I have not found a fix and I've had a couple of direct emails from others seeing the same issue.  I believe @SteveClement is researching.

**Comment by SteveClement** [comment]
Ok, I just tried to export (Download as) from a new install and id just worked.

It should propose you to download a file named:

misp.all.event_1.intel

Where _1 is the event id.

**Comment by jdeluzio** [comment]
Hi,

I'm not sure what I'm doing wrong.  I just downloaded the latest version
I've added a single event.
[image: image.png]

If I then go to export I can generate for everything but bro.

[image: image.png]

If I go to Jobs, bro always fails the same way.  I've tried every piece of
troubleshooting I can find online.

[image: image.png]
Does Bro require something different than all the others?

Thanks,

Jamey

**Comment by weslambert** [comment]
Any progress on this @jdeluzio @SteveClement?

I've had this same issue for a while now (Clicking `Generate` for Bro in the Export section of the UI results in a failed job).  This used to work, however, it appears it's still broken for me.  

Tested yesterday using training VM `MISP_v2.4.103@28bafcc47f0b20693d60b1f4725c78f273000f16.ova` .  

To be honest, I haven't done a ton of scrounging around, but wanted to check if this was resolved before really digging in.

Thanks,
Wes

**Comment by jdeluzio** [comment]
Hi,

I'm getting a lot of questions about MISP.

Thanks!

**Comment by iglocska** [comment]
It is bro via the API or the generated caches that barf?

**Comment by SteveClement** [comment]
@jdeluzio I do not see the screenshots. As it works for me I cannot really help without more details.

**Comment by iglocska** [comment]
reproduced via the generated caches. Will try to dig into this asap.

**Comment by iglocska** [comment]
Just pushed a fix for this, could you retest with it?

**Comment by weslambert** [comment]
@iglocska  while I can't speak for @jdeluzio, I've confirmed your recent commit fixes this issue for me.

Thanks,
Wes

**Comment by jdeluzio** [comment]
Hi,

This also resolved my main issues, not sure about the extra header lines being generated but that may be working as designed or an option I'm missing somewhere.  This is the file with a single event.  Other than that I'm now able to generate bro/zeek intel files... Thanks!!!

#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
www.google.ru	Intel::DOMAIN	MISP (5c87d96e-77b4-4b30-b8e7-0c04c0a8d58e) - ORGNAME	Control_Group. 	/events/view/1	T	-	-
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in

**Comment by weslambert** [comment]
Right, the original issue is resolved, but I too am now receiving the export with multiple header lines -- this is, however, only for Intel exported via the GUI.  The API seems to work fine for me, which is all I really need at the moment.

Thanks,
Wes

**Comment by jdeluzio** [comment]
Thanks, Wes, I'll give the API a try.  @iglocska are those extra header lines when exporting in the GUI expected?

**Comment by befrankt** [comment]
Thanks so much, I can confirm the export (and generation) of BRO intel now works.

**Comment by iglocska** [comment]
Ah i see. Will fix that soon

**Comment by jdeluzio** [comment]
@iglocska would you like me to close this case out and open one for that specific issue?  Or just work from this one?

**Comment by SteveClement** [comment]
this is fixed in the latest commit.

**Comment by jdeluzio** [comment]
@SteveClement @iglocska - This issue appears to be back in the lasted MISP_v2.4.104@6f3a9b2b6d0427105927231528b5a1a5384ffa11.  I'm back to being able to generate everything but bro.  

Can this be re-opened or should I open a new issue?

**Comment by iglocska** [comment]
Reopened. Bloody hell.

**Comment by iglocska** [comment]
I must have screwed it up whilst trying to fix the other ones.

**Comment by jdeluzio** [comment]
@iglocska 

Just checking back on this one, any updates?

**Comment by iglocska** [comment]
Sorry for the delay, should be fixed now!

**Comment by adulau** [comment]
@weslambert Can you confirm everything is now fine for you? Just found https://buildmedia.readthedocs.org/media/pdf/securityonion/latest/securityonion.pdf and the issue is still mentioned in the securityonion documentation. Thank you very much.
