### ISSUE TITLE
REST API not working with a JSON POST request

### ISSUE THREAD

**Issue by Rafiot** [MISP/MISP#407]
If I try to sent a query on <URL>/events/restSearch/download, the output is always:
{u'message': u'/events/restSearch/download', u'name': u'An Internal Error Has Occurred.'}

Query example:
{"from": "2015-02-15", "type": "ip-src", "value": "1.1.1.1", "to": "2015-02-16"}

**Comment by adulau** [comment]
As additional information: "An Internal Error Has Occurred" ->  Error: Fatal Error (1): Maximum execution time of 60 seconds exceeded in ../MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php.

**Comment by iglocska** [comment]
That sounds correct, though not really obvious at first why:

Basically, MISP expects the object to be encapsulated in a "request".

Give it a shot with: 

{"request": {"from": "2015-02-15", "type": "ip-src", "value": "1.1.1.1", "to": "2015-02-16"}}

and it should work. What happens otherwise is that it basically doesn't detect any of the arguments and it tries to return the entire database visible to your user as a JSON, during which it times out.

Let me know if that doesn't fix it for you!

**Comment by Rafiot** [comment]
Ok, that one works.

Other working examples: 
{"request": {"from": "2014-01-01", "value": "8.8.8.8", "to": "2015-02-16"}}
{"request": {"from": "2014-01-01", "type": "ip-src", "to": "2015-02-16"}}

Non-working example (time-out):
{"request": {"from": "2014-02-15", "to": "2015-02-16"}}

**Comment by Rafiot** [comment]
and as we are at it, I'm not sure if I do the query properly, but /events/attributes/returnAttributes does not seems to work either:
{"request": {"sigOnly": false, "id": 1859}}
=> {u'name': u'Not Found', u'url': u'/events/attributes/returnAttributes'}

**Comment by iglocska** [comment]
Gah, was a bit too slow, noticed the returnattribute issue too, just git pull :) 

I'll look into the time-out with just the dates set.

**Comment by adulau** [comment]
Thanks for the update.

After a git pull, it seems that is not only the template missing but the controller handler.

2015-02-16 14:47:34 Error: [MissingActionException] Action EventsController::attributes() could not be found.
Exception Attributes: array (
  'controller' => 'EventsController',
  'action' => 'attributes',
)
Request URL: /events/attributes/returnAttributes
Stack Trace:
#0 MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(185): Controller->invokeAction(Object(CakeRequest))
#1 MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(160): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#2 MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}

**Comment by iglocska** [comment]
You have a mistake in your request URL:

/events/attributes/returnAttributes

It should be /attributes/returnAttributes

Otherwise it will be looking for the attributes() function in the Events
controller.

**Comment by Rafiot** [comment]
Ok, I don't think this one is useful in the API so I will just not implement it.

**Comment by iglocska** [comment]
The return_attributes API? It was something that was specifically needed
for the maltego plugin, I don't think it is really used for anything
outside of it :)

**Comment by iglocska** [comment]
Non-working example (time-out):
{"request": {"from": "2014-02-15", "to": "2015-02-16"}}



- Should be fixed now. I was running into crazy timeouts on it (720 sec timeout limit hit on our MISP). With the latest version I got it down to 1:15

**Comment by Rafiot** [comment]
That's better, but I still have an issue: the PHP library does not return valid JSON. 

Is : 
{"response":[{"Event":.......}{"Event":.......}....]}

Should be:
{"response":[{"Event":.......},{"Event":.......}....]}

As you can see, the comma is missing.

**Comment by iglocska** [comment]
Ah indeed. Let me fix it fast!

**Comment by adulau** [comment]
@iglocska Is json_encode working properly? or the default array_push not working as expected?

~~~~
	$jsonArray['response']['Event'][] = $result['Event'];
}
echo json_encode($jsonArray);
~~~~

Thank you

**Comment by iglocska** [comment]
Hello there, sorry for the delay, json_encode works fine, it was my mistake that caused it:

I build each event separately now and then simply keep adding the json_encoded version to a string, I simply left off the delimiting comma. This way we can keep the memory usage down and the performance is much better than just building a massive object and then converting it in one go.
