### ISSUE TITLE
Export API is broken

### ISSUE THREAD

**Issue by worldopener** [MISP/MISP#4070]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Debian
| OS version (client)       | 9.7
| PHP version               | 7.0.33
| MISP version / git hash   | 2.4.101, 52d787f23514dc2aff0e16fcc8a56ad05ebb2ffa
| Browser                   | Firefox

### Expected behavior
REST API calls create an export

### Actual behavior
NIDS exports (https://misp.test/events/stix/download.json) creates this error:

```
2019-01-31 11:31:17 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Lib/Export/NidsExport.php, line 651]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
NidsExport::checkWhitelist() - APP/Lib/Export/NidsExport.php, line 651
NidsExport::ipDstRule() - APP/Lib/Export/NidsExport.php, line 213
NidsExport::domainIpRule() - APP/Lib/Export/NidsExport.php, line 206
NidsExport::export() - APP/Lib/Export/NidsExport.php, line 177
NidsSnortExport::export() - APP/Lib/Export/NidsSnortExport.php, line 12
Attribute::nids() - APP/Model/Attribute.php, line 2103
EventsController::nids() - APP/Controller/EventsController.php, line 2713
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

STIX exports (https://misp.test/events/stix/download.json) create this error:

```

2019-01-31 11:29:15 Error: [Exception]
Request URL: /events/stix/download.json
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

### Steps to reproduce the behavior
for stix:

`curl -k --header "Authorization: AUTHKEY" --header "Accept: application/json" --header "Content-Type: application/json" -X POST https://misp.test/events/stix/download.json -d '{"request": {"from":"2019-01-01","to":"2019-01-02"}}'`

for NIDS:

`curl -k --header "Authorization: AUTHKEY" https://misp.test/events/nids/snort/download`

**Comment by worldopener** [comment]
the NIDS export is fixed with the latest commit, stix export still doesn't work, i get:

`{"name":"An Internal Error Has Occurred.","message":"An Internal Error Has Occurred.","url":"\/events\/stix\/download.json"}`


```
2019-01-31 12:18:29 Error: [Exception]
Request URL: /events/stix/download.json
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

```

**Comment by iglocska** [comment]
That API is deprecated, could you use restSearch instead?

**Comment by iglocska** [comment]
I've pushed a fix for /events/stix but generally not advised to use that - stick to /events/restSearch

**Comment by worldopener** [comment]
there is no mention in the documentation that it's deprecated. How can i get the same output with restSearch?

BTW i still get:

```
2019-01-31 14:09:02 Error: [BadRequestException] Bad Request
Request URL: /events/stix/download.json
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```
also generating the stix/stix2 file from the "Event Actions->Export" leads to

`2019-01-31 14:15:05 Warning: fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5697]`

which leads to a stix/stix2 file that is empty

Will test cases get implemented to catch bugs/regressions like this?

**Comment by iglocska** [comment]
There should be no mention of this API in the documentation anymore. Are you looking at /events/automation ? 

To get the same output in restSearch:

POST to /events/restSearch

payload should be:
```
{
  "returnFormat": "stix",
  //.. all your other parameters
}
```

You can test your queries using the rest client's templating system. For further documentation for the API refer to the automation page (event actions -> automation).

**Comment by worldopener** [comment]
But is there something planned to add test cases, to find these regressions before changes get commited to the main tree?

I was reading the documentation pdf i downloaded some months ago.

Generating the stix/stix2 file from the "Event Actions->Export" still leads to

`2019-01-31 14:15:05 Warning: fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5697]`

and the created file is 0 bytes in size

I also still get:

```
2019-01-31 17:29:26 Error: [BadRequestException] Bad Request
Request URL: /events/stix/download.json
Stack Trace:
#0 [internal function]: EventsController->stix('download')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
```

And 

`/events/restSearch  -d '{"returnFormat": "stix", "id":"4809"}'` (the id exists) just created another backtrace

```
2019-01-31 17:39:17 Warning: Warning (2): fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5697]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fread - [internal], line ??
Event::restSearch() - APP/Model/Event.php, line 5697
EventsController::restSearch() - APP/Controller/EventsController.php, line 3097
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

**Comment by iglocska** [comment]
It sounds like something went wrong with the execution of the STIX library. Could you check the diagnostics if they are reporting any issues? (Administration -> server settings -> diagnostics).

Also, fr the second query, you can pass the event's ID via the "eventid" key rather than "id".

**Comment by worldopener** [comment]
I have no warning or Error on the diagnostics page:

![unbenannt](https://user-images.githubusercontent.com/46495009/52203907-dff0e500-2872-11e9-82aa-7e70e7b4194e.PNG)
After updating to the lastet git commit it get:

for https://misp.test/events/nids/snort/download (although it outputs valid data), it outputs multiples errors like this:

```
2019-02-04 11:39:45 Warning: Warning (2): Invalid argument supplied for foreach() in [/var/www/MISP/app/Lib/Export/NidsExport.php, line 651]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
NidsExport::checkWhitelist() - APP/Lib/Export/NidsExport.php, line 651
NidsExport::ipSrcRule() - APP/Lib/Export/NidsExport.php, line 234
NidsExport::export() - APP/Lib/Export/NidsExport.php, line 153
NidsSnortExport::export() - APP/Lib/Export/NidsSnortExport.php, line 12
Attribute::nids() - APP/Model/Attribute.php, line 2107
EventsController::nids() - APP/Controller/EventsController.php, line 2713
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```

For stix (curl -k --header "Authorization: xxx" --header "Accept: application/json" --header "Content-Type: application/json" -X POST https://misp.test/events/restSearch  -d '{"returnFormat": "stix", "eventid":"4809"}') i get:
```
2019-02-04 11:50:36 Warning: Warning (2): fread(): Length parameter must be greater than 0 in [/var/www/MISP/app/Model/Event.php, line 5697]
Trace:
ErrorHandler::handleError() - APP/Lib/cakephp/lib/Cake/Error/ErrorHandler.php, line 230
fread - [internal], line ??
Event::restSearch() - APP/Model/Event.php, line 5697
EventsController::restSearch() - APP/Controller/EventsController.php, line 3097
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 491
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 193
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 167
[main] - APP/webroot/index.php, line 92
```
