### ISSUE TITLE
Bro Exporter produces superfluous header artifacts

### ISSUE THREAD

**Issue by pbartruff** [MISP/MISP#4641]
Folks,
The Bro Exporter seems to be producing header artifacts:

It appears this was mentioned/fixed, yet reverted in another fix noted in the following issue:
#4050

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CentOS 7
| OS version (client)       | Windows 10 (Chrome?)
| PHP version               | 7.2.18
| MISP version / git hash   | 2.4.107, hash of the commit
| Browser                   | Chrome
### Expected behavior
One event header!
Regardless, if there is one or more events, the output should only have one header line and follow the Intel log format as defined by Bro/Zeek [https://docs.zeek.org/en/stable/frameworks/intel.html](url)
> #fields indicator       indicator_type  meta.source     meta.desc       meta.url
1.2.3.4 Intel::ADDR     source1 Sending phishing email  http://source1.com/badhosts/1.2.3.4
a.b.com Intel::DOMAIN   source2 Name used for data exfiltration -

### Actual behavior
Several headers with only one event.
> #fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
13.45.23.92	Intel::DOMAIN	Talon Solutions MISP (5cdcae15-7650-4dc1-bd59-1e99c0a80416) - Talon Solutions	Le bad IP. 	http://misp.talon-solutions.net:8888/events/view/1	T	-
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in

### Steps to reproduce the behavior
Manually create a domain event, add attributes, publish event, go to exporter and generate Bro output, download file, review the odd behavior :-P

### Logs, screenshots, configuration dump, ...
Noted above.

**Comment by jdeluzio** [comment]
I'm definitely seeing the same issue.

**Comment by rommelfs** [comment]
@liviuvalsan Could you have a look if you have some time? Could be your area of expertise ;)

**Comment by jdeluzio** [comment]
@rommelfs @liviuvalsan Any updates on this issue, I verified it still exists in the latest version.

Thanks

**Comment by butterball7469** [comment]
Seeing this issue, seems like 5-6 random #fields lines inserted through the file.  This doesn't seem to affect the API download of the bro formatted file.

**Comment by jdeluzio** [comment]
@rommelfs @liviuvalsan any updates on this issue? 

Thanks

**Comment by rommelfs** [comment]
I can't reproduce this any longer on 2.4.113.

**Comment by pbartruff** [comment]
@rommelfs Are you saying you can't reproduce, because you are now on 2.4.113, or this is no longer present because it was fixed somewhere in between 2.4.107 and 2.4.113?  If it is the former, I can try and reproduce it for you; however, I can't fix it!  I found several suspect locations in the code, but my PHP debugging is terrible!

**Comment by rommelfs** [comment]
@pbartruff I don't know if it was fixed between 2.4.107 and 2.4.113. 
All I'm saying is that I tried to reproduce the issue with the information you have given and I cannot reproduce on 2.4.113.
Can you still reproduce it on 2.4.113?

**Comment by jdeluzio** [comment]
@rommelfs @pbartruff I just tested with the vmware 2.4.119 and the issue is still present.  

This was a very simple test of adding a single attribute and then exporting as bro.

#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
www.google.ru	Intel::DOMAIN	ORGNAME MISP (5df27e10-89fc-48ba-ad1b-055ec0a8d581) - ORGNAME	Control. 	https://192.168.213.129:8443/events/view/3	T	-
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in

**Comment by rommelfs** [comment]
Tested on 2.4.119:

Added new event, added attribute, published event, exported event:
```
#fields	indicator	indicator_type	meta.source	meta.desc	meta.url	meta.do_notice	meta.if_in
www.google.ru	Intel::DOMAIN	CIRCL MISP (5df33678-1c08-4c2c-9556-410d950d210f) - CIRCL	test bro. 	https://misppriv.circl.lu/events/view/64191	T	-
```

**Comment by mayurkaura** [comment]
I also observed same issue .I went to  Export and clicked Generate for Bro intel format type and then downloaded file . I tried to upload intel file to Corelight Zeek Sensor and it gave error … I searched file and it had repeated header information once . I removed duplicate entries and that worked .

**Comment by iglocska** [comment]
WIll have a look this is weird.

**Comment by iglocska** [comment]
Indeed, it was bugged. Should be fixed now, please pull the latest version.

**Comment by RichieB2B** [comment]
This was fixed in 17918f916ceb54f7e8c13cbe73d6e795424337f4
