### ISSUE TITLE
Invalid Dashboard link and DB issues

### ISSUE THREAD

**Issue by coolacid** [MISP/MISP#5695]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | CoolAcid's Docker
| OS version (client)       | Ubuntu
| PHP version               | 7.3
| MISP version / git hash   | 2.4.123
| Browser                   | If applicable

### Expected behavior
Load the new dashboard

### Actual behavior
Error: The requested address '/users/dashboard' was not found on this server.

### Steps to reproduce the behavior
- Start MISP
- Global -> My Profile
- Click `Dashboard` on left nav
- Error

the Link should probably link to `/dashboards` not '/users/dashboard'

**Comment by collinhunter** [comment]
Also getting an issue in Diagnostics: Warning The MISP database state does not match the expected schema. Resolving these issues is recommended.


Table name | Description | Expected schema | Actual schema |  
dashboards
--
Table `dashboards` is an additional table

**Comment by drmcrooks** [comment]
For completeness, having also updated to 123, I'm seeing these version numbers in Diagnostics:

Expected DB_version: 49 Actual DB_version: 48

EDIT: I'm using the Harvard IT docker image

**Comment by iglocska** [comment]
The dashboard link should be fixed already - however the db version is curious. Will see if i can reproduce it.

**Comment by drmcrooks** [comment]
Thanks!

**Comment by collinhunter** [comment]
I’m getting Expected DB_version: 49 Actual DB_version: 49 and the View Dashboard link is fixed.

I'm using the MISP docker image (XME) and updated to 123 also.

But I’m still having an issue with the Database schema diagnostic x (red). and the Reveal benign deltas shows dashboards in the table below

**Comment by iglocska** [comment]
Could you show the output?

**Comment by coolacid** [comment]
Fresh docker container:
Expected and Actual are version 49
Benign Delta includes `Table 'dashboards' is an additional table`

![image](https://user-images.githubusercontent.com/1091410/76523035-1158be80-643e-11ea-9086-42bbbf20fb8a.png)

Both `dashboards` and `sightingdbs` are missing from https://github.com/MISP/MISP/blob/2.4/INSTALL/MYSQL.sql

`dashboards` is missing from https://github.com/MISP/MISP/blob/2.4/db_schema.json

Edit: Fix grammar and quoting. This is what I get for working pre-coffee.

**Comment by collinhunter** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by collinhunter** [comment]
Here is what I'm seeing
![screenshot](https://user-images.githubusercontent.com/47120957/76533139-5d176200-6456-11ea-8bf9-5ae645b168aa.png)

**Comment by coolacid** [comment]
^ is because `dashboards` is missing from the `db_schema.json` file.

**Comment by drmcrooks** [comment]
I wanted to check back in on this to ask if there were any suggestions on the best way for us to update our DB version from 48 to 49 safely (or indeed if we're better holding off for the moment - it's not affecting our main usage)?

**Comment by raw-data** [comment]
@coolacid @iglocska same issue here, while upgrading from 2.4.121 to 2.4.123, any tips on how to fix this?

**Comment by coolacid** [comment]
@raw-data Which issue, there is two issues tracked here:
1. The invalid link (Solved in next release)
2. DB Version mismatch (Not really an issue, just a notice in admin panel)

**Comment by coolacid** [comment]
For reference, the invalid link is fixed in https://github.com/MISP/MISP/commit/cc36cc5991657256fce259b0f7121c31ea1684c2

**Comment by raw-data** [comment]
Hi @coolacid, thank you for the prompt reply. 

- Clicking _Global Actions_ -> _Dashboard_, returns  "An Internal Error has occurred" 
- Checking /var/www/MISP/app/tmp/logs/error.log

`Error: [MissingTableException] Table dashboards for model Dashboard was not found in datasource default.

Exception Attributes: array (
  'table' => 'dashboards',
  'class' => 'Dashboard',
  'ds' => 'default',
)
Request URL: /dashboards`

- Checking _Diagnostics_, under _Server Settings & Maintenance_ shows an issue in the _Schema status_, -> Expected_DB_version:49 (in green) and Actual_DB_version: 47 (in red)

**Comment by coolacid** [comment]
@raw-data That is not related to this issue. However, it appears you're not running latest DB version. 

I don't know how to force the update. Try google, the MISP Gitter support channel (https://gitter.im/MISP/Support) or open your own issue.

**Comment by raw-data** [comment]
@coolacid JFI, reverting the system to a previous state and upgrading from that point (basically as it was done at the beginning) this time worked.  The _dashboards_ table gets created, and _DB_version_ is now consistent.

No idea what went wrong the first time ... since actions were exactly the same in both cases, anyhow, thanks for the tips.
