### ISSUE TITLE
Rules with pull request are ignored

### ISSUE THREAD

**Issue by cudeso** [MISP/MISP#5730]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu
| PHP version               | 7.2
| MISP version / git hash   | 2.4.120

### Expected behavior

Follow the pull rules (ignore events with a specific tag, only sync those with a specific tag).

### Actual behavior

All events are synced (pulled), regardless of the tag.

### Steps to reproduce the behavior

The taxonomy was not locally enabled.
Tried with tags escaped and not escaped: same result.
Only when adding the rule as additional sync parameter the tag selection was followed.

### Logs, screenshots, configuration dump, ...
<img width="691" alt="Screenshot_26_03_2020__13_49" src="https://user-images.githubusercontent.com/256028/77648564-a42e4880-6f68-11ea-9a77-ee615b399385.png">

**Comment by JamesSOC080** [comment]
This was fixed under: https://github.com/MISP/MISP/issues/5594. Upgrading to v.2.4.121 fixed it - however having updated this afternoon to latest commit (on v2.4.123) it seemed to come back.

**Comment by iglocska** [comment]
Is it the latest commit or the tagged version @2.4.123? It should be fixed as of yesterday again (so latest commit on HEAD should get you sorted) - if it doesn't let me know!

**Comment by JamesSOC080** [comment]
@iglocska - so I've just updated now (through the GUI), commit: d48a013f3a06c740a03ac16cdd4e256f2f0763c7

The issue remains, whereby when the server pull is initiated it appears to be pulling ALL events from the sync server - despite a rule I have limiting it to just pulling events from a given Organisation on that server.

**Comment by iglocska** [comment]
Hmm indeed. I had a look ad it is indeed an issue for orgs specifically, it's a similar yet somewhat different issue compared to the one for tags. I've added a fix but the problem is that the remote side needs to handle it correctly - so that needs to be updated. Which server are you pulling from, anything under our control?

**Comment by iglocska** [comment]
OK, nevermind. Added a hacky work-around when syncing with all prior versions, could you git pull again?

**Comment by JamesSOC080** [comment]
@iglocska - yep latest pull seems to have fixed the issue.

For info the remote server is currently running v2.4.121.

**Comment by iglocska** [comment]
Perfect, thanks for the heads up :)

**Comment by iglocska** [comment]
Closing the issue for now, if it resurfaces please open a new one! ;)
