### ISSUE TITLE
Malware Sample and Advanced Extraction No Longer Displays SSDEEP or PE file sections

### ISSUE THREAD

**Issue by malwaredevil** [MISP/MISP#5807]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | Ubuntu 18.04
| OS version (client)       | Ubuntu 18.04
| PHP version               | 7.2,7.3,7.4
| MISP version / git hash   | 2.4.124
| Browser                   | If applicable

### Expected behavior
Upload Attachment and check"is malware" and "advanced extraction". It should show ssdeep and all PE sections' information.

### Actual behavior
Only shows base hashes for file

### Steps to reproduce the behavior
Create an Incident
Add and attachment
Select both checkboxes (identifying it as malware and advanced extraction)

**Comment by Rafiot** [comment]
Can you check if `pydeep` and `lief` are correctly installed in the diagnostic page?

**Comment by malwaredevil** [comment]
They all have the green OK beside them. 

Also, I have had this issue using the vmware image (MISP_v2.4.124@cff666f-VMware), docker image(Harvard-Security/MISP), vagrant install(MISP\misp-vagrant), and ubuntu 18.04 brand new installs (https://misp.github.io/MISP/INSTALL.ubuntu1804/). I checked the different new installs just to make sure it wasn't just my Ubuntu 18.04 install's error. It seems like a misp-wide issue.

**Comment by malwaredevil** [comment]
I don't know if it helps, but I was using version 2.4.114 and it worked fine. When I created a new MISP instance (2.4.124) using the INSTALL scripts/methods (mentioned in my previous post), it no longer works as expected (showing each of the pe sections and their associated stats/hashes).

**Comment by Rafiot** [comment]
Right, there is in fact something broken, we will work on it asap.

For future debugging: `$tmpfile->path` says the file is in `/tmp`, but the file is not there. The method creating the lightweight file object directly uses $tmpfile, and doesn't care about the file on disk itself.

**Comment by Rafiot** [comment]
@Malvoce can you try to update PyMISP in the virtual environment? it may be a problem related to the locale and I fixed that in a recent release.

**Comment by malwaredevil** [comment]
@Rafiot: I will do a brand new install and report back as soon as I have results. My environment will be Ubuntu 18.04
PHP 7.4.5
fully updated/upgraded
Using directions: https://misp.github.io/MISP/INSTALL.ubuntu1804/

**Comment by malwaredevil** [comment]
@Rafiot  See my next comment my testing results. Up front, it didn't fix the issue:

**Comment by malwaredevil** [comment]
# INSTALL ENVIRONMENT AND RESULTS:

**VIRTUALIZATION SOFTWARE**: VIRTUAL BOX 6.0.20 R137117
**OS**: UBUNTU 18.04
**PHP**: 7.2, 7.3, AND 7.4
**BROWSER**: MOZILLA FIREFOX FOR UBUNTU (75.0) CANONICAL - 1.0
**TESTING RECOMMENDATION**:
Update pymisp in virtual environment

**RESULTS**:
1. PHP 7.2: **FAIL** [SEE BELOW FOR PROCEDURE]
1. PHP 7.3: **N/A** [MISP INSTALL SCRIPT UPGRADES 7.3 TO 7.4]
1. PHP 7.4: **FAIL** [SEE BELOW FOR PROCEDURE]


## PYTHON 7.2
**RESULT**: FAIL

### PRE MISP INSTALL MODIFICATIONS:PRE MISP INSTALL MODIFICATIONS:
1. UPDATE AND UPGRADE ALL PACKAGES

### INSTALL MISP
1. INSTALLATION COMMANDS
```bash
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M -S
```

### POST MISP INSTALL MODIFICATIONS
1. APACHE2 & CLI INCREASE FILE SIZE LIMITS AND EXECUTION TIMES DUE TO LARGE MALWARE REQUIREMENTS:
```bash
sudo sed -i "s/memory_limit = -1/memory_limit = 2048M/" /etc/php/7.2/apache2/php.ini ; \
sudo sed -i "s/upload_max_filesize = 50M/upload_max_filesize = 50000M/" /etc/php/7.2/apache2/php.ini ; \
sudo sed -i "s/post_max_size = 50M/post_max_size = 50000M/" /etc/php/7.2/apache2/php.ini; \
sudo sed -i "s/max_execution_time = 30/max_execution_time = 3000/" /etc/php/7.2/cli/php.ini ; \
sudo sed -i "s/memory_limit = -1/memory_limit = 2048M/" /etc/php/7.2/cli/php.ini ; \
sudo sed -i "s/upload_max_filesize = 50M/upload_max_filesize = 50000M/" /etc/php/7.2/cli/php.ini ; \
sudo sed -i "s/post_max_size = 50M/post_max_size = 50000M/" /etc/php/7.2/cli/php.ini;
```
1. FIX "CONNECTION REFUSED" ON ENRICHMENT MODULE SYSTEM, IMPORT MODULE SYSTEM, EXPORT MODULE SYSTEM
```bash
sudo apt install cmake -y
cd /usr/local/src/misp-modules
sudo chgrp www-data .
sudo chmod g+w .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
sudo chgrp staff .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I .
cd /usr/local/src
sudo rm -rf faup
sudo -H -u misp -g staff git clone git://github.com/stricaud/faup.git faup
cd faup
sudo -H -u misp -g staff mkdir -p build
cd build
sudo -H -u misp -g staff cmake .. && sudo -H -u misp -g staff make
sudo make install
sudo ldconfig
cd /usr/local/src/faup/src/lib/bindings
sudo chown -R www-data:www-data python
cd python
sudo -H -u www-data /var/www/MISP/venv/bin/python3 setup.py install
```
1. RESTART/VERIFY APACHE2
```bash
systemctl restart apache2
```
1. RESTART/VERIFY MISP MODULES
```bash
systemctl restart misp-modules.service
```

### TESTING RECOMMENDATIONS AND RESULT
#### UPDATE PYMISP WITH PIP3 IN VENV 
##### UPDATE PROCEDURE
1. BASIC UPDATE AND THEN INDIVIDUAL OPTIONAL COMPONENENTS
```bash
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[fileobjects]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[neo]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[openioc]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[virustotal]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[docs]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[pdfexport]
```

##### RESULT OF PYMISP UPDATE
1. BASIC UPDATE
A. NO UPDATE PERFORMED AS PIP INDICATED IT WAS ALREADY UP TO DATE [FAIL]
1. UPDATE WITH OPTIONS
	- **FILEOBJECTS**: NO UPDATE [FAIL]
	- **NEO**: [FAIL]
	- **OPENIOC**: NO UPDATE [FAIL]
	- **VIRUSTOTAL**: NO UPDATE [FAIL]
	- **DOCS**: [FAIL]
	- **PDFEXPORT**: NO UPDATE [FAIL]

##### PROCESS AFTER UPDATE TO TEST
1. REBOOT VM
1. TRY ADDING EVENT AND ATTACHING INNOCUOUS PE TO EXTRACT SECTIONS AND SSDEEP: (FileZilla_Pro_3.47.2.1_win64-setup.EXE, size: 8.7MB)
1. CREATE NEW EVENT NAMED "test"
1. SELECT ADD ATTACHMENT
1. CATEGORY:  Payload Delivery
1. Distribution: Inherit event
1. BROWSE > SELECTED ATTACHMENT
1. CHECK "Is a malware sample..." and "Advanced extraction..."
1. CLICK UPLOAD

**NOTE**: A FAIL RESULT IS RESULT WHEN THERE IS NO SSDEEP OR PE SECTIONS CREATED AFTER UPLOAD.

## PYTHON 7.4
**RESULT**: FAIL

### PRE MISP INSTALL MODIFICATIONS
1. UPDATE AND UPGRADE ALL PACKAGES

1. INSTALL PHP 7.4 VIA FOLLOWING COMMANDS
```bash
sudo apt install software-properties-common
sudo add-apt-repository ppa:ondrej/php -y
sudo apt update
sudo apt install -y \
		libapache2-mod-php7.4 \
		php7.4 \
		php7.4-cli \
		php7.4-dev \
		php7.4-json \
		php7.4-xml \
		php7.4-mysql \
		php7.4-opcache \
		php7.4-readline \
		php7.4-mbstring \
		php-redis \
		php-gnupg \
		php-gd
sudo apt update
sudo apt upgrade -y
```

### INSTALL MISP
1. INSTALLATION COMMANDS
```bash
wget -O /tmp/INSTALL.sh https://raw.githubusercontent.com/MISP/MISP/2.4/INSTALL/INSTALL.sh
bash /tmp/INSTALL.sh -c -M -S
```


### POST MISP INSTALL MODIFICATIONS

1. APACHE2 & CLI INCREASE FILE SIZE LIMITS AND EXECUTION TIMES DUE TO LARGE MALWARE REQUIREMENTS
```bash
sudo sed -i "s/max_execution_time = 30/max_execution_time = 3000/" /etc/php/7.4/apache2/php.ini ; \
sudo sed -i "s/memory_limit = 128M/memory_limit = 2048M/" /etc/php/7.4/apache2/php.ini ; \
sudo sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 50000M/" /etc/php/7.4/apache2/php.ini ; \
sudo sed -i "s/post_max_size = 8M/post_max_size = 50000M/" /etc/php/7.4/apache2/php.ini; \
sudo sed -i "s/max_execution_time = 30/max_execution_time = 3000/" /etc/php/7.4/cli/php.ini ; \
sudo sed -i "s/memory_limit = 128M/memory_limit = 2048M/" /etc/php/7.4/cli/php.ini ; \
sudo sed -i "s/upload_max_filesize = 2M/upload_max_filesize = 50000M/" /etc/php/7.4/cli/php.ini ; \
sudo sed -i "s/post_max_size = 8M/post_max_size = 50000M/" /etc/php/7.4/cli/php.ini;
```
1. INSTALL/VERIFY SSDEEP FOR PHP 7.4.5
```bash
sudo sh -c "echo 'extension=ssdeep.so' >> /etc/php/7.4/mods-available/ssdeep.ini"
sudo phpenmod ssdeep
```

1. FIX *CONNECTION REFUSED*  ERROR ON ENRICHMENT MODULE SYSTEM, IMPORT MODULE SYSTEM, EXPORT MODULE SYSTEM
```bash
sudo apt install cmake -y
cd /usr/local/src/misp-modules
sudo chgrp www-data .
sudo chmod g+w .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I -r REQUIREMENTS
sudo chgrp staff .
sudo -H -u www-data /var/www/MISP/venv/bin/pip install -I .
cd /usr/local/src
sudo rm -rf faup
sudo -H -u misp -g staff git clone git://github.com/stricaud/faup.git faup
cd faup
sudo -H -u misp -g staff mkdir -p build
cd build
sudo -H -u misp -g staff cmake .. && sudo -H -u misp -g staff make
sudo make install
sudo ldconfig
cd /usr/local/src/faup/src/lib/bindings
sudo chown -R www-data:www-data python
cd python
sudo -H -u www-data /var/www/MISP/venv/bin/python3 setup.py install
```

1. RESTART/VERIFY APACHE2
```bash
systemctl restart apache2
```

1. RESTART/VERIFY MISP MODULES
```bash
systemctl restart misp-modules.service
```


### TESTING RECOMMENDATIONS AND RESULT
#### UPDATE PYMISP WITH PIP3 IN VENV 
##### UPDATE PROCEDURE
1. BASIC UPDATE AND THEN INDIVIDUAL OPTIONAL COMPONENENTS
```bash
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[fileobjects]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[neo]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[openioc]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[virustotal]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[docs]
sudo -H -u www-data /var/www/MISP/venv/bin/pip3 install -U pymisp[pdfexport]
```

##### RESULT OF PYMISP UPDATE
1. BASIC UPDATE
A. NO UPDATE PERFORMED AS PIP INDICATED IT WAS ALREADY UP TO DATE [FAIL]
1. UPDATE WITH OPTIONS
	- **FILEOBJECTS**: NO UPDATE [FAIL]
	- **NEO**:  NO UPDATE [FAIL]
	- **OPENIOC**: NO UPDATE [FAIL]
	- **VIRUSTOTAL**: NO UPDATE [FAIL]9
	- **DOCS**: [FAIL]
	- **PDFEXPORT**: NO UPDATE [FAIL]

##### PROCESS AFTER UPDATE TO TEST
1. REBOOT VM
1. TRY ADDING EVENT AND ATTACHING INNOCUOUS PE TO EXTRACT SECTIONS AND SSDEEP: (FileZilla_Pro_3.47.2.1_win64-setup.EXE, size: 8.7MB)
1. CREATE NEW EVENT NAMED "test"
1. SELECT ADD ATTACHMENT
1. CATEGORY:  Payload Delivery
1. Distribution: Inherit event
1. BROWSE > SELECTED ATTACHMENT
1. CHECK "Is a malware sample..." and "Advanced extraction..."
1. CLICK UPLOAD

**NOTE**: A FAIL RESULT IS RESULT WHEN THERE IS NO SSDEEP OR PE SECTIONS CREATED AFTER UPLOAD.

**Comment by Rafiot** [comment]
Thank you very much for the very detailed feedback, and sorry we didn't give you an update, but I think we know the issue: the encoding on the machine is incorrect.

What is the output of `localectl status`? 

```
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_LU.UTF-8
                  LC_TIME=de_LU.UTF-8
                  LC_MONETARY=de_LU.UTF-8
                  LC_PAPER=de_LU.UTF-8
                  LC_NAME=de_LU.UTF-8
                  LC_ADDRESS=de_LU.UTF-8
                  LC_TELEPHONE=de_LU.UTF-8
                  LC_MEASUREMENT=de_LU.UTF-8
                  LC_IDENTIFICATION=de_LU.UTF-8
       VC Keymap: n/a
      X11 Layout: us
       X11 Model: pc105
     X11 Variant: alt-intl
```

The important bit is that UTF-8 is mentioned. If it is not there, try to set the environment to `en_US.UTF-8`.

We will also fix PyMISP in order to enforce utf-8 everywhere.

**Comment by malwaredevil** [comment]
See below ` localectl status`:
``` 
System Locale: LANG=en_US.UTF-8
VC Keymap: n/a
X11 Layout: us
X11 Model: pc105
```

**Comment by malwaredevil** [comment]
Updated MISP to `v2.4.124 (a2928a09db9066f0aa3e33a759af48efec99f150) `. 
Unfortunately it is still broken on PHP 7.4.5 and 7.2

**Comment by mokaddem** [comment]
Hopefully your issue will be solved with this commit https://github.com/MISP/PyMISP/commit/f965e579d7303c9976b59ac5efa2c897c0ba6398.
You can either manually checkout the latest PyMISP version or wait the next MISP released where we will bump the submodules.

**Comment by malwaredevil** [comment]
# TEST: UPDATING SYSTEM DEFAULT PYTHON VERSION, UPDATING PYMISP, AND RESULTS
**Description**: Test setting system default to Python 3.6.9 and updating to latest version of PyMISP (see below for description of process)
**Results**:
- php7.2: **[PASS]**
- php7.4: **[PASS]**

## PHP 7.2
1. Update MISP from web interface

1. Set Python 3.6.9 to system Python default
```bash
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 20; \
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 10; \
sudo update-alternatives  --set python /usr/bin/python3.6;
```

1. Note Permisions
```bash
ls -la /var/www/MISP/PyMISP/pymisp/abstract.py /var/www/MISP/venv/src/pymisp/pymisp/abstract.py;
```

1. Git pull PYMISP
```bash
cd /var/www/MISP/venv/src/pymisp/; \
sudo git pull origin master; \
cd /var/www/MISP/PyMISP; \
sudo git pull origin master;\
sudo chown -R www-data:www-data  /var/www/; \
reboot;
```

1. Verify Permisions
```bash
ls -la /var/www/MISP/PyMISP/pymisp/abstract.py /var/www/MISP/venv/src/pymisp/pymisp/abstract.py;
```

1. Test
**[PASS]**



## PHP 7.4
1. Update MISP from web interface

1. Set Python 3.6.9 to system Python default
```bash
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 20; \
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.6 10; \
sudo update-alternatives  --set python /usr/bin/python3.6;
```

1. Note Permisions
```bash
ls -la /var/www/MISP/PyMISP/pymisp/abstract.py /var/www/MISP/venv/lib/python3.6/site-packages/pymisp/abstract.py /var/www/MISP/venv/src/pymisp/pymisp/abstract.py;
```

1. Git pull PYMISP
```bash
cd /var/www/MISP/venv/src/pymisp/; \
sudo git pull origin master; \
cd /var/www/MISP/PyMISP; \
sudo git pull origin master;\
sudo sed -i "s/with path.open('r') as f:/with path.open('r', encoding='utf-8') as f:/" /var/www/MISP/venv/lib/python3.6/site-packages/pymisp/abstract.py ; \
sudo chown -R www-data:www-data  /var/www/; \
reboot;
```

1. Verify Permisions
```bash
ls -la /var/www/MISP/PyMISP/pymisp/abstract.py /var/www/MISP/venv/lib/python3.6/site-packages/pymisp/abstract.py /var/www/MISP/venv/src/pymisp/pymisp/abstract.py;
```

1. Test
**[PASS]**

**Comment by Rafiot** [comment]
Thank you very much!

**Comment by malwaredevil** [comment]
Thank you too for resolving this!
