### ISSUE TITLE
Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UserSetting.setting' in 'where clause'

### ISSUE THREAD

**Issue by luna7391** [MISP/MISP#5838]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | RedHat 7.5
| OS version (client)       | Win10
| PHP version               | 7.4.5
| MISP version / git hash   | v2.4.116 (cc6bd68c5e3890f521ae9bec3c51826ee39264d3)
| Browser                   | Issue seen in all browsers

### Support Questions
Hi. I'm trying to upgrade from v2.4.116 to v2.4.124 following Option 1 in https://misp.github.io/MISP/UPDATE/.  Post upgrade, when I launch the GUI I receive "An internal Error Has Occurred" in the browse rather than the logon screen.

### Logs, screenshots, configuration dump, ...
The orginal build was done following https://misp.github.io/MISP/INSTALL.rhel7/ as it was about 18 months ago. Previous upgrades were completed without issue including 2.4.112 -> 2.4.116.

DB version was v40 now v51 (had to run ./cake Admin cleanCache to update this)
DB is on separate MySQL DB Server and working fine prior to upgrade

I've also tried:
rm -f /var/www/MISP/app/tmp/cache/models/myapp*
rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*

and checked permissions with:

find   /var/www/MISP -type d -exec chmod g=rx {} \;
chmod -R g+r,o= /var/www/MISP/
chown -R apache:apache   /var/www/MISP/

### Error:
2020-04-28 15:07:20 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UserSetting.setting' in 'where clause'
Request URL: /users/checkIfLoggedIn.json
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `UserSet...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `UserSet...', Array, Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `UserSet...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(UserSetting), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/AppController.php(540): Model->find('first', Array)
#7 /var/www/MISP/app/Controller/UsersController.php(30): AppController->beforeFilter()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by iglocska** [comment]
OK, that is indeed weird, the steps you took would have been those I'd recommend. Could you check if the table and column are actually present in your DB? That way we can rule out caching issues.

**Comment by luna7391** [comment]
Thanks iglocska, I appreciate your response.
+-------------------------------+---------------+
| table_name                    | MB            |
+-------------------------------+---------------+
| admin_settings                |    0.01562500 |
| attributes                    |  556.98437500 |
| attribute_tags                |   44.06250000 |
| bruteforces                   |    0.01562500 |
| cake_sessions                 |    0.03125000 |
| correlations                  |    0.14062500 |
| dashboards                    |    0.09375000 |
| decaying_models               |    0.10937500 |
| decaying_model_mappings       |    0.03125000 |
| events                        |   47.67187500 |
| event_blacklists              |    0.04687500 |
| event_delegations             |    0.04687500 |
| event_locks                   |    0.06250000 |
| event_tags                    |   11.54687500 |
| favourite_tags                |    0.04687500 |
| feeds                         |    0.09375000 |
| fuzzy_correlate_ssdeep        |    0.04687500 |
| galaxies                      |    0.07812500 |
| galaxy_clusters               |    0.14062500 |
| galaxy_elements               |    0.09375000 |
| galaxy_reference              |    0.07812500 |
| inbox                         |    0.10937500 |
| jobs                          |    0.01562500 |
| logs                          | 1639.00000000 |
| news                          |    0.01562500 |
| noticelists                   |    0.04687500 |
| noticelist_entries            |    0.03125000 |
| notification_logs             |    0.04687500 |
| objects                       |    9.06250000 |
| object_references             |    6.76562500 |
| object_relationships          |    0.03125000 |
| object_templates              |    0.09375000 |
| object_template_elements      |    0.04687500 |
| organisations                 |    0.09375000 |
| org_blacklists                |    0.01562500 |
| posts                         |    0.04687500 |
| regexp                        |    0.01562500 |
| rest_client_histories         |    0.06250000 |
| roles                         |    0.01562500 |
| servers                       |    0.06250000 |
| shadow_attributes             |    0.15625000 |
| shadow_attribute_correlations |    0.12500000 |
| sharing_groups                |    0.07812500 |
| sharing_group_orgs            |    0.04687500 |
| sharing_group_servers         |    0.04687500 |
| sightingdbs                   |    0.07812500 |
| sightingdb_orgs               |    0.04687500 |
| sightings                     |    0.10937500 |
| tags                          |    0.20312500 |
| tag_collections               |    0.06250000 |
| tag_collection_tags           |    0.04687500 |
| tasks                         |    0.01562500 |
| taxonomies                    |    0.04687500 |
| taxonomy_entries              |    0.51562500 |
| taxonomy_predicates           |    0.09375000 |
| templates                     |    0.01562500 |
| template_elements             |    0.01562500 |
| template_element_attributes   |    0.01562500 |
| template_element_files        |    0.01562500 |
| template_element_texts        |    0.01562500 |
| template_tags                 |    0.01562500 |
| threads                       |    0.07812500 |
| threat_levels                 |    0.01562500 |
| users                         |    0.06250000 |
| user_settings                 |    0.06250000 |
| warninglists                  |    0.01562500 |
| warninglist_entries           |    0.03125000 |
| warninglist_types             |    0.01562500 |
| whitelist                     |    0.01562500 |
+-------------------------------+---------------+
69 rows in set (0.01 sec)

Not sure if I'm checking the right table:
SHOW COLUMNS FROM user_settings;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int(11)      | NO   | PRI | NULL    | auto_increment |
| key       | varchar(100) | NO   | MUL | NULL    |                |
| value     | text         | YES  |     | NULL    |                |
| user_id   | int(11)      | NO   | MUL | NULL    |                |
| timestamp | int(11)      | NO   | MUL | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
5 rows in set (0.10 sec)

**Comment by iglocska** [comment]
Ok, wow, I see. I also see the culprit. Will push a fix within the hour.

**Comment by iglocska** [comment]
Should be fixed now if you git pull

**Comment by luna7391** [comment]
Unfortunately I'm still getting the same error:
The DB version is still at 51

2020-04-29 15:20:04 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'UserSetting.setting' in 'where 

clause'
Request URL: /users/login
Stack Trace:
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('SELECT `UserSet...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(715): DboSource->execute('SELECT `UserSet...', Array, 

Array)
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(1226): DboSource->fetchAll('SELECT `UserSet...', Array)
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3053): DboSource->read(Object(UserSetting), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(3025): Model->_readDataSource('first', Array)
#6 /var/www/MISP/app/Controller/AppController.php(544): Model->find('first', Array)
#7 /var/www/MISP/app/Controller/UsersController.php(30): AppController->beforeFilter()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(244): UsersController->beforeFilter(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(682): CakeEventManager->dispatch(Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(189): Controller->startupProcess()
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object

(CakeRequest))
#12 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#13 {main}

**Comment by RichieB2B** [comment]
Should have been fixed with d2ed0c89566c9e6f6adf8789377ecdb8b73ed40a

**Comment by luna7391** [comment]
Hi RichieB2B,

After re-running the git pull and checking the user_settings table I can see that there's still a 'key' field, should this have changed to 'settings'?

MySQL []> SHOW COLUMNS FROM user_settings;
+-----------+--------------+------+-----+---------+----------------+
| Field     | Type         | Null | Key | Default | Extra          |
+-----------+--------------+------+-----+---------+----------------+
| id        | int(11)      | NO   | PRI | NULL    | auto_increment |
| key       | varchar(100) | NO   | MUL | NULL    |                |
| value     | text         | YES  |     | NULL    |                |
| user_id   | int(11)      | NO   | MUL | NULL    |                |
| timestamp | int(11)      | NO   | MUL | NULL    |                |
+-----------+--------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

**Comment by iglocska** [comment]
Looks like i was in error (mixed up user and admin settings) so the fix didn't actually do anything. Will have a look at it in a few hours, need to grab some shut eye.

**Comment by iglocska** [comment]
OK, it should be fixed this time around, could you git pull again?

**Comment by luna7391** [comment]
Many thanks, will try again and provide an update shortly.

**Comment by luna7391** [comment]
The upgrade has worked successfully to v2.4.125. However I'm getting the following Workers status:

Worker type: cache
Jobs in the queue: 0

Queue status: OK
Worker PID 	User 	Worker process 	Information 	Actions
2435 	apache 	Dead 	The Worker appears to be dead. 	
Worker type: default
Jobs in the queue: 0

Queue status: OK
Worker PID 	User 	Worker process 	Information 	Actions
2399 	apache 	Dead 	The Worker appears to be dead. 	
Worker type: email
Jobs in the queue: 0

Queue status: OK
Worker PID 	User 	Worker process 	Information 	Actions
2453 	apache 	Dead 	The Worker appears to be dead. 	
Worker type: prio
Jobs in the queue: 0

Queue status: OK
Worker PID 	User 	Worker process 	Information 	Actions
2417 	apache 	Dead 	The Worker appears to be dead. 	
Worker type: update
Jobs in the queue: 0

Queue status: Issues prevent jobs from being processed. Please resolve them below.
Worker PID 	User 	Worker process 	Information 	Actions
N/A 	N/A 	N/A 	Worker not running! 	 
Worker type: scheduler
Worker PID 	User 	Worker process 	Information 	Actions
2471 	apache 	Dead 	The Worker appears to be dead.

The server has been rebooted and su - apache -s /bin/bash -c 'bash /var/www/MISP/app/Console/worker/start.sh' seems to work ok:

Stopping workers
Stopping the Scheduler Worker ... Done
Stopping 3072 ... Done
Stopping 2991 ... Done
Stopping 3052 ... Done
Stopping 3032 ... Done
Stopping 3012 ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating workers
Starting worker ... Done

Creating the scheduler workers
Starting scheduler worker ... Done

**Comment by luna7391** [comment]
Hi, anybody able to assist - Still experiencing the above worker issue, resque-scheduler log doesn't seem to show any issues but GUI still only shows the dead sessions. Only experienced since the above upgrade to v2.4.125.

[2020-05-01 10:28:30] main.INFO: *** Starting scheduler worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port","queues":["_schdlr_"]} []
[2020-05-01 10:28:30] main.INFO: Starting worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port:_schdlr_"} []
[2020-05-01 10:30:50] main.INFO: Exiting... {"type":"shutdown","worker":"mispinstance:port"} []
[2020-05-01 10:30:52] main.INFO: *** Starting scheduler worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port","queues":["_schdlr_"]} []
[2020-05-01 10:30:52] main.INFO: Starting worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port:_schdlr_"} []
[2020-05-01 10:31:46] main.INFO: Exiting... {"type":"shutdown","worker":"mispinstance:port"} []
[2020-05-01 10:31:48] main.INFO: *** Starting scheduler worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port","queues":["_schdlr_"]} []
[2020-05-01 10:31:48] main.INFO: Starting worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port:_schdlr_"} []
[2020-05-01 10:33:30] main.INFO: Exiting... {"type":"shutdown","worker":"mispinstance:port"} []
[2020-05-01 10:33:32] main.INFO: *** Starting scheduler worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port","queues":["_schdlr_"]} []
[2020-05-01 10:33:32] main.INFO: Starting worker mispinstance:port:_schdlr_ {"type":"start","worker":"mispinstance:port:_schdlr_"} []

**Comment by luna7391** [comment]
Not sure if the above could be anything to do with the following: 
![image](https://user-images.githubusercontent.com/38982979/81174293-83aad280-8f99-11ea-8f3f-88a980891bf7.png)

Anyone able to advise on both of the above? Thanks.

**Comment by iglocska** [comment]
Ping @mokaddem

**Comment by mokaddem** [comment]
Hey @luna7391 could you try to restart the workers via the web interface? Clicking the `restart dead workers` should prune dead workers and start new ones.
Also I see that you are using the built-in scheduler. Unfortunately, it is no longer maintained. I really encourage you to use CRON jobs for all these tasks. You will gain in flexibility and granularity of when you want them to execute.
Also, did you by any chances perform manual modification in the MySQL database?

**Comment by luna7391** [comment]
Hi @mokaddem, thanks for your response.

Yes I've tried the 'restart dead workers' but unfortunately this doesn't resolve the issue. As mentioned above it has only been since the update from v2.4.116 to v2.4.124 that I've experienced the issue, previously running the above command line to restart them has worked.

No manual modifications have been made to the MySQL database. I did have issues with the first couple of upgrade attempts as the DB wasn't being updated from v40, I think clearing the Cache prior to a new update attempt helped to resolve that(?). The DB is currently v53. There had also been the issue with user_settings.setting field not updating from 'key' until the code change.

I actually use a CRON job to push/pull events between a share partner and between my External and Internal MISP instances.
Thanks.

**Comment by mokaddem** [comment]
By looking at the last log entries you posted, it's the log of the scheduler. Since your are using CRON jobs you should not worry about it.
However, your db diagnostic screenshot is concerning, especially if you haven't touched the DB manually. 
It could also explain why you were missing the `setting` column in your `UserSetting` table that @iglocska fixed. 

I really advice you to fix the database schema. 
The safest way is to downgrade your DB version to `12` then re-execute the update by log in in the instance.
I said `12` because it seems that the inconsistencies started from that point. (`event_graph` table was created in update `13`)
```
# Downgrade db_version to 12
UPDATE admin_settings SET db_version=12 WHERE setting='db_version';
```

**Comment by luna7391** [comment]
Hi @mokaddem, the command above didn't work but I tried the following and the version reverted to 12.
UPDATE admin_settings SET db_version=12 WHERE db_version=53;

Result:

- Tried GUI logon, received error 503 Service Unavailable, the DB version had updated to 45.

- Tried GUI logon again after about 10 mintes, this was fine and DB version had updated to 53.

- DB schema now shows:
![image](https://user-images.githubusercontent.com/38982979/82232516-a5f00900-9926-11ea-9ae9-2e55f51ac87e.png)

- At the moment I'm still getting the above error with the workers....running "su - apache -s /bin/bash -c 'bash /var/www/MISP/app/Console/worker/start.sh' " looks ok but the interface still states "Issues prevent jobs from being processed."

**Comment by luna7391** [comment]
Hi, I'm still experiencing the worker issue above where they seem to stop and start ok with the CLI command and no errors are being reported, however the workers are still reporting " Issues prevent jobs from being processed. Please resolve them below." in the UI. My MISP instance is now at v2.4.129.

The Schema Status is also still showing "Column `orgc_id` is indexed but should not", should this be mitigated with the "DROP INDEX `orgc_id` ON feeds;" or d it be left as is? Table is showing " orgc_id           | int(11)      | NO   | MUL | 0   ". 

Advise would be appreciated, thanks.

**Comment by mokaddem** [comment]
@luna7391 I fixed the warning about `orgc_id` not being indexed. It was indeed a missing entry in the base schema. Thanks!
As for your workers issue if you still have it, could you open another issue?
Thanks!
