### ISSUE TITLE
updateWarningLists: Undefined indexes and packet bigger than 'max_allowed_packet' bytes 

### ISSUE THREAD

**Issue by JoePJisc** [MISP/MISP#6252]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Support
| OS version (server)       | CentOS
| OS version (client)       | Win10
| PHP version               | 7.2.27
| MISP version / git hash   | v2.4.129 (c0bc1a0c67bffc91cfa7382bb5df3d6bb39a42cd)
| Browser                   | Google Chrome

### Support Questions

I have migrated a v2.4.127 MISP instance (that's been running about 3 years) out of Docker to use the amuehlem/MISP-RPM approach (clean install -> imported database -> imported app/files directory -> git fetch run for misp-galaxy, misp-objects, noticelists, taxonomies, and warninglists -> updated python dependencies -> added missing ssdeep and zip PHP modules); despite the database reporting it was at the expected DB_version (55), there where quite a few inconsistencies, all of which have been fixed.

The diagnostics page has gone from a myriad of warnings and errors down to:

* Version warning (the RPM hasn't caught up to v2.4.130 yet).
* The expected "not using git" and PHP verison warnings.

Despite the platform operating as expected, with no unexpected errors on the diagnostics page, I am unable to update the warning lists via the Web UI or cake; trying to do this via cake gives the clearest output, which is:

```bash
$ sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateWarningLists

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Notice Error: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 66]

2020-08-28 17:15:07 Notice: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 66]
Notice Error: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 114]

2020-08-28 17:15:07 Notice: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 114]
Notice Error: Undefined index: description in [/var/www/MISP/app/Model/Warninglist.php, line 114]

2020-08-28 17:15:07 Notice: Undefined index: description in [/var/www/MISP/app/Model/Warninglist.php, line 114]
Notice Error: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 78]

2020-08-28 17:15:07 Notice: Undefined index: name in [/var/www/MISP/app/Model/Warninglist.php, line 78]
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(89): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(110): Warninglist->quickDelete('75')
#6 /var/www/MISP/app/Model/Warninglist.php(71): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Console/Command/AdminShell.php(187): Warninglist->update()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateWarningLists()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateWarningLi...', Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#12 {main}
```

Updating taxonomies, galaxies, and noticelists via the Web UI works as expected.

Any suggestions to fix warning list updates would be appreciated.

### Logs, screenshots, configuration dump, ...

```sql
MariaDB [misp]> DESCRIBE warninglists;
+-------------------------+------------------+------+-----+---------+----------------+
| Field                   | Type             | Null | Key | Default | Extra          |
+-------------------------+------------------+------+-----+---------+----------------+
| id                      | int(11)          | NO   | PRI | NULL    | auto_increment |
| name                    | varchar(255)     | NO   |     | NULL    |                |
| type                    | varchar(255)     | NO   |     | string  |                |
| description             | text             | NO   |     | NULL    |                |
| version                 | int(11)          | NO   |     | 1       |                |
| enabled                 | tinyint(1)       | NO   |     | 0       |                |
| warninglist_entry_count | int(11) unsigned | YES  |     | NULL    |                |
+-------------------------+------------------+------+-----+---------+----------------+
7 rows in set (0.01 sec)
```

```sql
MariaDB [misp]> DESCRIBE warninglist_entries;
+----------------+---------+------+-----+---------+----------------+
| Field          | Type    | Null | Key | Default | Extra          |
+----------------+---------+------+-----+---------+----------------+
| id             | int(11) | NO   | PRI | NULL    | auto_increment |
| value          | text    | NO   |     | NULL    |                |
| warninglist_id | int(11) | NO   | MUL | NULL    |                |
+----------------+---------+------+-----+---------+----------------+
3 rows in set (0.00 sec)
```

**Comment by iglocska** [comment]
Could you try the following?

````
rm -f /var/www/MISP/app/files/cache/persistent/myapp*
rm -f /var/www/MISP/app/files/cache/model/myapp*
````

**Comment by JoePJisc** [comment]
Unable to do those exact commands as `/var/www/MISP/app/files/cache` does not exist, however, there is a `tmp/cache`, tried the below, but the update still fails with the same notices and error.

```bash
#!/bin/bash
set -e
cd /var/www/MISP/app/tmp/
sudo tar cfz /tmp/MISPCache.tar.gz cache/
sudo rm -f /var/www/MISP/app/tmp/cache/persistent/myapp*
sudo rm -f /var/www/MISP/app/tmp/cache/model/myapp*
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateWarningLists
```

**Comment by JoePJisc** [comment]
I have just encountered a similar same issue on a second server (no Undefined indexes, but still packet bigger than 'max_allowed_packet' bytes).

The second server was a clean install from RPM to v2.4.129, with only a few users and no events added so far, I have just upgraded it to v2.4.130 via RPM, output of `updateJSON` for that host below.

```bash
$ sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateJSON

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Updating all JSON structures.
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(89): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(110): Warninglist->quickDelete('47')
#6 /var/www/MISP/app/Model/Warninglist.php(71): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Model/Server.php(5937): Warninglist->update()
#8 /var/www/MISP/app/Console/Command/AdminShell.php(137): Server->updateJSON()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateJSON()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateJSON', Array)
#11 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#12 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#13 {main}`

**Comment by JoePJisc** [comment]
On that second server, all other JSON updates work:

```bash
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateGalaxies # OK
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateNoticelists # OK
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateWarninglists # FAILS
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateTaxonomies # OK
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateObjectTemplates 1 # OK
```

**Comment by JoePJisc** [comment]
Having upgraded to v2.4.132 this issue is still present.

**Comment by mokaddem** [comment]
Hello,
I tried to reproduce your issue without success.
- Would you mind making sure that your warninglist repository is aligned to the HEAD pointed by the MISP repository
- Could you also tell us what are the enabled warninglist when performing the update
- And finally, paste the relevant error log with the commit id

Thanks in advance!

**Comment by JoePJisc** [comment]
Sorry I haven't updated this sooner, I am experiencing this issue on 3 instances, all now running v2.4.135 via MISP-RPM.

Hopefully the below helps

# HEAD alignment 

I cannot tell; I assume these are maintained by the RPM?

```bash
# cd /var/www/MISP/app/files/warninglists/
# git status
fatal: Not a git repository (or any of the parent directories): .git
```

# Enabled warning lists

Across the 3 instances enabled lists are:
1. None.
2. Covid-19 Cyber Threat Coalition's Whitelist.
2. List of known IPv4 public DNS resolvers, List of known Office 365 IP address ranges, List of known Office 365 URLs, Covid-19 Cyber Threat Coalition's Whitelist, List of known Cloudflare IP ranges, List of known Amazon AWS IP address ranges, Top 1000 website from Alexa, List of known Windows 10 connection endpoints, List of known microsoft domains, List of known google domains, List of known URL Shorteners domains, List of known Office 365 URLs address ranges, List of known gmail sending IP ranges, University domains, List of known Googlebot IP ranges, Top 1000 website from Cisco Umbrella, List of known Office 365 URLs and IP address ranges

# Error

```
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(206): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(227): Warninglist->quickDelete('72')
#6 /var/www/MISP/app/Model/Warninglist.php(188): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Console/Command/AdminShell.php(187): Warninglist->update()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateWarningLists()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateWarningli...', Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#12 {main}
```

**Comment by JoePJisc** [comment]
Interestingly, clicking on the top warning list on one of these instances returns `Error: The requested address '/Warninglist/view/174' was not found on this server.`

The row in question is:

ID | Name | Version | Description | Type | Valid attributes | Entries
-- | -- | -- | -- | -- | -- | --
174 | TLDs as known by IANA | 20201123 | Event contains one or more TLDs as attribute with an IDS flag set | string | hostname, domain, domain\|ip | 1507

**Comment by mokaddem** [comment]
Hi,
Reported issue about address not found has been fixed in 4c6445acb89a6177d8417e775694bce32061e310.
Thanks for the report

**Comment by JoePJisc** [comment]
I've just upgraded to v2.4.137 and I'm still seeing:

```
# sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateWarninglists

Welcome to CakePHP v2.10.22 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(206): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(227): Warninglist->quickDelete('72')
#6 /var/www/MISP/app/Model/Warninglist.php(188): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Console/Command/AdminShell.php(187): Warninglist->update()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateWarningLists()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateWarningli...', Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#12 {main}
```

**Comment by JoePJisc** [comment]
I'm still having this issue across the 3 servers above, is it possible for this to be reopened?

If you need any further detail let me know,

after v2.4.140 upgrade

```bash
sudo -H -u apache /var/www/MISP/app/Console/cake Admin updateWarninglists

Welcome to CakePHP v2.10.24 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(209): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(230): Warninglist->quickDelete('72')
#6 /var/www/MISP/app/Model/Warninglist.php(191): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Console/Command/AdminShell.php(187): Warninglist->update()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateWarningLists()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateWarningli...', Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#12 {main}
```

**Comment by Tyrell20** [comment]
Same error on my MISP instance (v2.4.140):

 MISP/app/Console/cake Admin updateWarningLists

```
Welcome to CakePHP v2.10.24 Console
---------------------------------------------------------------
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: SQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes
#0 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(502): PDOStatement->execute(Array)
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/DboSource.php(468): DboSource->_execute('DELETE `Warning...', Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/Database/Mysql.php(459): DboSource->execute('DELETE `Warning...')
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Model.php(2885): Mysql->delete(Object(WarninglistEntry), ' WHERE `Warning...')
#4 /var/www/MISP/app/Model/Warninglist.php(209): Model->deleteAll(Array)
#5 /var/www/MISP/app/Model/Warninglist.php(230): Warninglist->quickDelete('77')
#6 /var/www/MISP/app/Model/Warninglist.php(191): Warninglist->__updateList(Array, Array)
#7 /var/www/MISP/app/Console/Command/AdminShell.php(187): Warninglist->update()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): AdminShell->updateWarningLists()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand('updateWarningLi...', Array)
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(32): ShellDispatcher::run(Array)
#12 {main}
```

It is possible to reopen this issue?
Thank you

**Comment by JoePJisc** [comment]
@PROTechThor / @mokaddem can this be reopened?

**Comment by JoePJisc** [comment]
I have not seen this issue in the last few updates, so closing the issue.

Thanks
