### ISSUE TITLE
Security.allow_unsafe_apikey_named_param setting doesn't work

### ISSUE THREAD

**Issue by iwitz** [MISP/MISP#7179]
# This template is meant for bug reports, if you have a feature request user the other template.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | RHEL7
| OS version (client)       | Win10
| PHP version               | 7.3
| MISP version / git hash   | 2.4.140
| Browser                   | Any

### Expected behavior
The configuration page states for this setting :
"Allows passing the API key via the named url parameter "apikey"

-> When querying the REST API through the GUI (not the included API client), the "apikey" GET parameter should be set and results returned.

### Actual behavior
The apikey GET parameter isn't set. Events cannot be downloaded when this setting is enabled.

### Steps to reproduce the behavior

1. Enable the Security.allow_unsafe_apikey_named_param option
2. Try to download an event
3. The event isn't downloaded and the requested URL doesn't contain

This is especially an issue because if I understand this option correctly, it could be a workaround for issue #7178

**Comment by Wachizungu** [comment]
This should be fixed now I believe, see https://github.com/MISP/MISP/commit/eebe0310916a6c54f7387cb9499b72e21c4d8688

Did a quick test myself and it seems to be working on latest version (I don't use this functionality myself normally).

**Comment by iwitz** [comment]
I pulled the latest version (I'm on commit eebe031 at the time of this writing) and tried to download an event but I still have the issue.
I looked into the Apache logs to see if it might have removed URL parameters and in Firefox to see if the parameter appeared in the requested URL, but I couldn't find any trace of the "apikey" URL parameter either in the client browser or on the server :(

@Wachizungu how did you test the fix ? I can try to do the same thing and see if I get the same result.

**Comment by Wachizungu** [comment]
Strange
while logged out from the instance I did:

https://[my_url]/events/restSearch/returnFormat:json/eventid:[my_eventid]/apikey:[my_key]

**Comment by iwitz** [comment]
It works for me too if I add my API key manually. I thought the "Download as" button would send the API key in the URL automatically with this option enabled, but since the setting's description states that it _allows_ sending the API key in the URL, and not that it makes it the default, I will close the issue.
Thank you both !
