### ISSUE TITLE
"Cake Admin setSetting disable_emailing true" not working

### ISSUE THREAD

**Issue by galaxyjams** [MISP/MISP#7477]
I can't set disable_emailing using the Cake Admin command

First do

**cake Admin getSetting “MISP.disable_emailing”**

Welcome to CakePHP v2.10.24 Console

App : app
Path: /var/www/MISP/app/

{
    “level”: 0,
    “description”: “You can disable all e-mailing using this setting. When enabled, no outgoing e-mails will be sent by MISP.“,
    “value”: false,
    “errorMessage”: “”,
    “null”: true,
    “test”: “testDisableEmail”,
    “type”: “boolean”,
    “tab”: “MISP”,
    “setting”: “MISP.disable_emailing”
}

Then

**cake Admin setSetting “MISP.disable_emailing” true**

Welcome to CakePHP v2.10.24 Console

App : app
Path: /var/www/MISP/app/

E-mailing is blocked.

Then running the first command still says disable_emailing  is false

This is on misp 2.4.139

**Comment by righel** [comment]
Hello,
Since MISP version `2.4.142` you can use the `--force` option to override some safety checks when updating settings via de console. Try running:
`cake Admin setSetting MISP.disable_emailing true --force`

**Comment by galaxyjams** [comment]
Hi,

Thanks for the reply but I am currently using 2.4.139.

The issue is that the setSetting says it has blocked emailing but it has not.

Thanks

**Comment by chrisinmtown** [comment]
Please explain more @righel what is the safety check on disable_emailing that has to be overridden?   I would like to set this setting without forcing it. Here's the code that answers the confusing message:

https://github.com/MISP/MISP/blob/d426c8ec319e206d4a38a748637a5759a8f8e4a8/app/Model/Server.php#L1734

I need to send in "True" to disable email.  The value is normally set to false.  What is really being tested here by function testDisableEmail() ?  The function always answers false when given a value of True, which seems to block the set action.  

If I'm correct that this function is deficient, then please check the next function in the file, testDisableCache(), which seems to have exactly the same behavior, it always returns false when invoked with value true.

Sure looks like a bug to me, but this issue has been awaiting triage for 6 weeks at this point :(

**Comment by iglocska** [comment]
Changed the behaviour, basically it's a soft failure. MISP considers emailing being completely disabled as an error, so it will not allow the change to go through without forcing it, though the response was trash. I've changed the response to clearly throw an error with an explanation:

![image](https://user-images.githubusercontent.com/3668672/126958041-d844dbe0-3d32-4fea-b5d5-3192d0916a31.png)

As @righel suggested, passing --force will override it as in this case you are clear about the implications and still want to enforce the change.

**Comment by iglocska** [comment]
Also, this is only on develop for now, so it will be in the next release (though only the feedback changed, you can already force the change).

**Comment by galaxyjams** [comment]
cake Admin setSetting MISP.completely_disable_correlation true — force

does not work

The setting change was rejected. MISP considers the requested setting value as invalid and would lead to the following error:

“%s”

This is in 2.4.147

cake Admin setSetting MISP.language eng fails and fails similar to above with the —force option. I.e the error being “%s”

Any ideas ?

**Comment by christophercutajar** [comment]
> cake Admin setSetting MISP.completely_disable_correlation true — force
> 
> does not work
> 
> The setting change was rejected. MISP considers the requested setting value as invalid and would lead to the following error:
> 
> “%s”
> 
> This is in 2.4.147
> 
> cake Admin setSetting MISP.language eng fails and fails similar to above with the —force option. I.e the error being “%s”
> 
> Any ideas ?

The same is happening to me whereby when trying use `--force`, MISP is still rejecting the change

```bash
sudo -u www-data /var/www/MISP/app/Console/cake  Admin setSetting "MISP.language" "eng" --force
```

Log:

```
App : app
Path: /var/www/MISP/app/
---------------------------------------------------------------
Error: Setting change rejected.
The setting change was rejected. MISP considers the requested setting value as invalid and would lead to the following error:
"%s"
If you still want to force this change, please supply the --force argument.
```

Any suggestions how to tackle this issue would help! Thanks

**Comment by iglocska** [comment]
Should be fixed, thanks!

**Comment by iglocska** [comment]
https://github.com/MISP/MISP/commit/269883c4ef7f5e8ffa15f2e1fc8eff5fb243bfd7

**Comment by christophercutajar** [comment]
I have rebuild MISP from source-code to be able to get this change but I'm still experiencing the same issue! This is my new comamnd:

```bash
sudo -u www-data /var/www/MISP/app/Console/cake  Admin setSetting "MISP.language" "eng" --force
```

**Comment by christophercutajar** [comment]
I had to comment out this config to be able to start up MISP once again!

> I have rebuild MISP from source-code to be able to get this change but I'm still experiencing the same issue! This is my new comamnd:
> 
> ```shell
> sudo -u www-data /var/www/MISP/app/Console/cake  Admin setSetting "MISP.language" "eng" --force
> ```
