### ISSUE TITLE
Discussions in v2.4

### ISSUE THREAD

**Issue by h122015** [MISP/MISP#768]
I have a question regarding the Discussions in version 2.4. How is it planned to use this functionality? 

Logged in as Admin I started a new thread (Discussions -> Start discussion) and another user should reply to it. When the user logs in, he only sees the titles of the current threads but he cannot reply to any of the listed threads neither see their contents, since there are no buttons or links to do so. 

I'd like also to report a couple of issues I found while playing around when commenting events.

If I add a new event as a regular user and in that event I try to submit a comment  I see the following in the debug and error logs. 

==> debug.log <==
2015-12-17 09:57:29 Notice: Notice (8): Undefined index: org_id in [/var/www/MISP/app/Controller/ThreadsController.php, line 103]
Trace:
ThreadsController::view() - APP/Controller/ThreadsController.php, line 103
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 165
Object::requestAction() - APP/Lib/cakephp/lib/Cake/Core/Object.php, line 106
RequestHandlerComponent::beforeRedirect() - APP/Lib/cakephp/lib/Cake/Controller/Component/RequestHandlerComponent.php, line 271
ObjectCollection::trigger() - APP/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php, line 128
call_user_func - [internal], line ??
CakeEventManager::dispatch() - APP/Lib/cakephp/lib/Cake/Event/CakeEventManager.php, line 242
Controller::redirect() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 765
PostsController::add() - APP/Controller/PostsController.php, line 162
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 92

==> error.log <==
2015-12-17 09:57:29 Error: [MethodNotAllowedException] Invalid Thread.
Request URL: /posts/add/event/64
Stack Trace:
#0 [internal function]: ThreadsController->view('64', '1')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest))
#4 /var/www/MISP/app/Lib/cakephp/lib/Cake/Core/Object.php(106): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
#5 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/RequestHandlerComponent.php(271): Object->requestAction('/threads/view/6...', Array)
#6 [internal function]: RequestHandlerComponent->beforeRedirect(Object(PostsController), Array, NULL, true)
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Utility/ObjectCollection.php(128): call_user_func_array(Array, Array)
#8 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Event/CakeEventManager.php(242): call_user_func(Array, Object(CakeEvent))
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(765): CakeEventManager->dispatch(Object(CakeEvent))
#11 /var/www/MISP/app/Controller/PostsController.php(162): Controller->redirect(Array)
#12 [internal function]: PostsController->add('event', '64')
#13 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#14 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#15 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#16 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#17 {main}

The funny thing is that the comment gets actually submitted, but only admin can see it. Regular users don't see the comment neither the text box and the following can be seen in the debug and error logs:

==> debug.log <==
2015-12-17 10:14:40 Notice: Notice (8): Undefined index: org_id in [/var/www/MISP/app/Controller/ThreadsController.php, line 103]
Trace:
ThreadsController::view() - APP/Controller/ThreadsController.php, line 103
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 92

==> error.log <==
2015-12-17 10:14:40 Error: [MethodNotAllowedException] Invalid Thread.
Request URL: /threads/view/65/true
Stack Trace:
#0 [internal function]: ThreadsController->view('65', 'true')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

Also if as admin I post a comment in one published event and then I delete it, there is no possibility for any regular user to add further comments since the text box disappears from the screen for that event. The debug and error logs show the following when I view a published event which got a comment deleted:
==> debug.log <==
2015-12-17 09:52:14 Notice: Notice (8): Undefined index: org_id in [/var/www/MISP/app/Controller/ThreadsController.php, line 103]
Trace:
ThreadsController::view() - APP/Controller/ThreadsController.php, line 103
ReflectionMethod::invokeArgs() - [internal], line ??
Controller::invokeAction() - APP/Lib/cakephp/lib/Cake/Controller/Controller.php, line 490
Dispatcher::_invoke() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 191
Dispatcher::dispatch() - APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php, line 165
[main] - APP/webroot/index.php, line 92

==> error.log <==
2015-12-17 09:52:14 Error: [MethodNotAllowedException] Invalid Thread.
Request URL: /threads/view/63/true
Stack Trace:
#0 [internal function]: ThreadsController->view('63', 'true')
#1 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(490): ReflectionMethod->invokeArgs(Object(ThreadsController), Array)
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(165): Dispatcher->_invoke(Object(ThreadsController), Object(CakeRequest))
#4 /var/www/MISP/app/webroot/index.php(92): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}

**Comment by iglocska** [comment]
I see what you mean, you can double click a discussion to view it, but it's not that obvious, will add a view button. Looking through the rest now.

**Comment by iglocska** [comment]
For the others, I've pushed some fixes yesterday for the discussions, could you git pull? Also, are you on the 2.4 branch or the 2.4 beta branch?

**Comment by h122015** [comment]
I'm currently on the 2.4 branch. I did the git pull, will test.

**Comment by h122015** [comment]
After the git pull I still have the first issue and the second one has somehow mutated. If as admin I post a comment, regular users can't neither see it nor post new comments since the text box is gone. If the admin removes the comment, now regular users see the text box and can post a comment, but then they land in the first issue.

**Comment by adulau** [comment]
Could you test with a recent version of MISP? I'll close the issue. Feel free to reopen the issue if required. Thank you.
