### ISSUE TITLE
Support: OpenID Connect Not Working/Docs Incomplete

### ISSUE THREAD

**Issue by jaimeatwork** [MISP/MISP#8598]
### Support Questions

I have attempted to configure OpenID connect but cannot seem to get it to work. 

I also had to enable Oidc auth in the bootstrap.php file by doing this

```
/**
 * Uncomment the following line to enable client SSL certificate authentication.
 * It's also necessary to configure the plugin �~@~T for more information, please read app/Plugin/CertAuth/reame.md
 */
CakePlugin::load('OidcAuth');
// CakePlugin::load('ShibbAuth');
// CakePlugin::load('LinOTPAuth');
```

My configuration, redacted:

```
....snip....
  'Security' =>
  array (
    'level' => 'medium',
....snip....
    'auth' =>
    array (
      0 => 'OidcAuth.Oidc',
    ),
....snip....
  array (
    'provider_url' => 'https://xxxx.xxxxxxxx.com', // sso provider
    'client_id' => 'client_id',
    'client_secret' => 'client_secret',
    'role_mapper' =>
    array (
      'misp-admin' => 1,
      'misp-user' => 3,
    ),
    'default_org' => 'MyOrg',
  ),
```

I consistently get the error `Error: invalid_client Description: The issuer of the request object is invalid.`. It does not appear any of the requests include the `iss` value in the URL or elsewhere I can see. 

Additionally, I tested from inside the deployment, I can curl to the wellknown OIDC endpoint and see the expected issuer key and value in the response. 

Do I need to take any specific steps to ensure the issuer is sent along? Thanks!

### MISP version

2.4.162

### Operating System

Ubuntu

### Operating System version

20.04

### PHP version

7.4.3

### Browser

Chrome

### Browser version

105

### Relevant log output

```shell
2022-09-20 20:38:03 Error: [JakubOnderka\OpenIDConnectClientException] Error: invalid_client Description: The issuer of the request object is invalid.
Request URL: /users/login?state=<redacted>&error=invalid_client&error_description=The+issuer+of+the+request+object+is+invalid.
Stack Trace:
#0 /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php(22): JakubOnderka\OpenIDConnectClient->authenticate()
#1 /var/www/MISP/app/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php(32): Oidc->authenticate()
#2 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(772): OidcAuthenticate->authenticate()
#3 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php(612): AuthComponent->identify()
#4 /var/www/MISP/app/Controller/UsersController.php(1199): AuthComponent->login()
#5 [internal function]: UsersController->login()
#6 /var/www/MISP/app/Lib/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(99): Dispatcher->dispatch()
#10 {main}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matthewpeyton** [comment]
I am also running into this issue. Is this an issue on the Okta setup side?

**Comment by nachorpaez** [comment]
I managed to get Okta working by applying this patch in the OpenID-Connect-PHP library `/var/www/MISP/app/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php`
```
--- OpenIDConnectClient.php	2022-09-20 09:41:00.050816667 -0700
+++ oidc_lib.php	2022-09-20 09:41:40.290986112 -0700
@@ -820,6 +820,8 @@
             'response_type' => 'code',
             'redirect_uri' => $this->getRedirectURL(),
             'client_id' => $this->clientID,
+	     'iss' => $this->clientID,
+	     'aud' => $this->getIssuer(),
             'nonce' => $nonce,
             'state' => $state,
             'scope' => 'openid'
```

And adding the `email` and `groups` scope in `/var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php`. Something like:
```
-- Oidc.php    2022-09-20 09:46:10.308122139 -0700
+++ patch.php   2022-09-20 09:24:51.006798204 -0700
@@ -294,7 +294,10 @@
 
         if ($this->getConfig('offline_access', false)) {
             $oidc->addScope('offline_access');
-        }
+       }
+
+       $oidc->addScope('email');
+       $oidc->addScope('groups');
 
         $oidc->setRedirectURL(Configure::read('MISP.baseurl') . '/users/login');
         $this->oidcClient = $oidc;
```

Okta relies on `iss` and `aud` to validate a request according to their docs (https://developer.okta.com/docs/reference/api/oidc/#parameter-details)

**Comment by matthewpeyton** [comment]
Can confirm @nachorpaez 's fix works.

**Comment by matthewpeyton** [comment]
Will this fix be included in a future release? My company is not going to sign off on me implementing this fix in a fork or manually on the box.

**Comment by eviltik** [comment]
What about adding `$oidc->addScope('roles');` too ? does it make sense ? if not, why ? perhaps groups is enought ?

Without groups and/or roles, MISP + Keycloak is not usable. So i agree with @matthewpeyton to hurry on this point. Thank you @nachorpaez ! thank you MISP team

**edit: after some changes related to claims keycloak side, everything works fine without any php modification.**

**Comment by pettai** [comment]
Thanks for this @nachorpaez

> And adding the `email` and `groups` scope in `/var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php`. Something like:
> 
> ```
> -- Oidc.php    2022-09-20 09:46:10.308122139 -0700
> +++ patch.php   2022-09-20 09:24:51.006798204 -0700
> @@ -294,7 +294,10 @@
>  
>          if ($this->getConfig('offline_access', false)) {
>              $oidc->addScope('offline_access');
> -        }
> +       }
> +
> +       $oidc->addScope('email');
> +       $oidc->addScope('groups');
>  
>          $oidc->setRedirectURL(Configure::read('MISP.baseurl') . '/users/login');
>          $this->oidcClient = $oidc;
> ```

(I'm not using Okta, but Satosa)
As you've pointed out MISP's OIDC never asks for scope email, which I think is a bit strange given that MISP says:
`2024-05-08 15:05:44 Error: [Exception] OIDC user 773052c053dec85f41a40f1cafd3f0a5aa47cd79663743c932de4c4ff32cdee9 doesn't have email address, that is required by MISP.` then I've successfully authenticated using OIDC.

(How could the current OIDC ever worked given the email scope is mandatory according to MISP itself? ping @JakubOnderka)

**Comment by CountyWorker** [comment]
I got this working thanks to info in this issue. Thanks guys! 

Some comments:

1. /var/www/MISP/app/Plugin/OidcAuth/Lib/Oidc.php

Added this line: $oidc->addScope('email') 

2. The setting 'scope' in /var/www/MISP/app/Plugin/config.php is not working?

3. The setting 'default_org' in /var/www/MISP/app/Plugin/config.php not working either...

4. There is a catch 22 issue here when activating SSO. If you want to change user information you need a password, but to get a password you have to add one to your profile. And that's not possible in SSO because you have none.

```
 'OidcAuth' =>
  array (
    'provider_url' => 'https://REDACTED',
    'issuer' => 'https://REDACTED',
    'client_id' => 'REDACTED',
    'client_secret' => 'REDACTED',
    'roles_property' => 'roles',
    'role_mapper' =>
    array (
      'misp-admin' => 1,
      'misp-user' => 3,
    ),
    'default_org' => 'REDACTED', // NOT WORKING
    'scopes' => ['openid','profile', 'email'], // NOT WORKING
  ),

```

Cheers!

**Comment by pettai** [comment]
It looks like this issue (at least part of it) was pulled in and fixed in MISP 2.5.0.
What version of MISP are you using?

**Comment by CountyWorker** [comment]
> It looks like this issue (at least part of it) was pulled in and fixed in MISP 2.5.0. What version of MISP are you using?

Yes, that's true. Running docker with version 2.4.195.

**Comment by egypcio** [comment]
FYI;

me and other folks are still facing this issue (to get SSO/OpenID) to work, either using Okta or Keycloak.

- MISP version 2.5 (ec9146444) -- installed using  the `INSTALL.ubuntu2404.sh` script;
- [jakub-onderka/openid-connect-php](https://packagist.org/packages/jakub-onderka/openid-connect-php) version 1.2.0.

for the following output, we have `debug` set to **2**;

```
Error 'invalid_client' received from IdP: The audience claim for client_assertion must be the endpoint invoked for the request.

Error: An Internal Error Has Occurred. Please try your action again. If the problem persists, please contact administrator.
Stack Trace

    APP/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php line 894 → JakubOnderka\OpenIDConnectClient->endpointRequest()
    APP/Vendor/jakub-onderka/openid-connect-php/src/OpenIDConnectClient.php line 557 → JakubOnderka\OpenIDConnectClient->requestAuthorization()
    APP/Plugin/OidcAuth/Lib/Oidc.php line 24 → JakubOnderka\OpenIDConnectClient->authenticate()
    APP/Plugin/OidcAuth/Controller/Component/Auth/OidcAuthenticate.php line 45 → Oidc->authenticate()
    APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 772 → OidcAuthenticate->authenticate()
    APP/Lib/cakephp/lib/Cake/Controller/Component/AuthComponent.php line 612 → AuthComponent->identify()
    APP/Controller/UsersController.php line 1257 → AuthComponent->login()
    [internal function] → UsersController->login()
    APP/Lib/cakephp/lib/Cake/Controller/Controller.php line 500 → ReflectionMethod->invokeArgs()
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 193 → Controller->invokeAction()
    APP/Lib/cakephp/lib/Cake/Routing/Dispatcher.php line 167 → Dispatcher->_invoke()
    APP/webroot/index.php line 107 → Dispatcher->dispatch()
```

![image](https://github.com/user-attachments/assets/7d06dad6-baa5-4516-a3dd-bdc3d5403d3e)

here's one piece of the `config.php` that may be relevant:

```php
  'Security' => 
  array (
    ...
    'auth' => array('OidcAuth.Oidc'),
    ...
  ),

  'OidcAuth' => 
  array (
    // 'login' => true,
    // 'unblock' => true,
    'offline_access' => true,
    'check_user_validity' => 300,
    // 'update_user_role' => true,
    'authentication_method' => 'client_secret_jwt',
    'code_challenge_method' => 'S256',
    'default_org' => 'ORGNAME',
    'scopes' => [ 'openid', 'profile', 'email', 'groups' ],
    'provider_url' => 'https://MYDOMAIN.okta.com/.well-known/openid-configuration',
    'issuer' => 'https://MYDOMAIN.okta.com',
    'client_id' => 'ABC',
    'client_secret' => 'X-Y-Z',
    'redirect_uri' => 'https://misp.MYDOMAIN.org/users/login',
    'role_mapper' => 
    array (
      'misp-sync-access' => 5,
      'misp-publisher-access' => 4,
      'misp-access' => 3,
      'misp-user' => 3,
      'misp-org-admin-access' => 2,
      'misp-admin' => 1,
      'misp-admin-access' => 1,
    ),
  ),
```

**Comment by egypcio** [comment]
FYI; the error changes once we do not have the `authentication_method` set like in the example above.

```
Error 'invalid_request' received from IdP: Cannot supply multiple client credentials.
Use one of the following: 
credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.
```

we are **not** using any environment variable or additional header on the Apache config.

**Comment by jonod8698** [comment]
@egypcio Did you get past `Error 'invalid_client' received from IdP: The audience claim for client_assertion must be the endpoint invoked for the request.` without unsetting `authentication_method`?

**Comment by egypcio** [comment]
> [@egypcio](https://github.com/egypcio) Did you get past `Error 'invalid_client' received from IdP: The audience claim for client_assertion must be the endpoint invoked for the request.` without unsetting `authentication_method`?

the value was different, and it was not set to **client_secret_jwt**.

based on the values presented by `token_endpoint_auth_methods_supported` (acquired via GET request against the provider URL, piped into `jq`) we ended up setting `authentication_method` to be **client_secret_post**

**Comment by jonod8698** [comment]
@egypcio Thank you! Was the rest of the configuration the same as https://github.com/MISP/MISP/issues/8598#issuecomment-2587332066 ?

**Comment by egypcio** [comment]
> [@egypcio](https://github.com/egypcio) Thank you! Was the rest of the configuration the same as [#8598 (comment)](https://github.com/MISP/MISP/issues/8598#issuecomment-2587332066) ?

not entirely, to be honest. sadly I can't grab the setup anymore as I left the project and lost access to the environment.

I may recommend you to start with the bare minimum, and simply add the `authentication_method` as mentioned above. later you move further and tweak your needs into the configuration file.
