### ISSUE TITLE
Bug: taxonomies/view Filter broken

### ISSUE THREAD

**Issue by github-germ** [MISP/MISP#8875]
### Expected behavior

The Filter on the View Taxonomy WebUI page for a given taxonomy no longer returns with matching rows.

It's working in 2.4.164, but not in 2.4.167.

### Actual behavior

 The `Loading` spinning wheel appears, but the resulting list is not limited to only matches as per the filter textbox.

### Steps to reproduce

Test the `Filter` on `taxonomies/view/nnn`

### Version

2.4.167

### Operating System

RH

### Operating System version

8.6

### PHP version

7.4.33

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adulau** [comment]
Indeed, good catch. I can reproduce it in 2.4.168.

**Comment by github-germ** [comment]
Hoping this can get fixed in the next release. Btw, the filter on `List Tags` works fine (i.e. `/tags/index`).

**Comment by github-germ** [comment]
@adulau I guess 2.4.168 is still "beta" as I didn't see an "official" email blast. Any idea on when that will occur or did I miss it? THANKS!!

**Comment by github-germ** [comment]
Problem persists in 2.4.170

**Comment by github-germ** [comment]
@adulau `Filter` on `MISP/taxonomies/view/nnn` still does not work with 2.4.171.

**Comment by github-germ** [comment]
Still broken in 2.4.172
Would be helpful to have this fixed in .173 as we have a very large custom taxonomy and searching is quite useful.
Thanks!

**Comment by github-germ** [comment]
@iglocska Any chance to take a look at this? Still broken in 2.4.174. We have a very large custom local taxonomy than spans many pages in WebUI view. It would be helpful if we could filter. Thanks.

**Comment by righel** [comment]
Should be fixed in the next release by this patch: https://github.com/MISP/MISP/pull/9233
Feel free to test it out and let me know if it works as expected.

**Comment by github-germ** [comment]
Cool. Thanks @righel

**Comment by github-germ** [comment]
2.4.177

@righel  ... Re-opening this as it partially fixed. Filter does work and displays the first page of matches. However, if there is more than one page, clicking `Next` or another page no longer displays matches.

**Comment by github-germ** [comment]
Works well with pagination now in 2.4.179. Thanks.
