### ISSUE TITLE
Bug: Proxy doesn't work as setting not correctly processed in CurlClient (call flow issue)

### ISSUE THREAD

**Issue by Benni0** [MISP/MISP#9550]
### Actual behavior

In MISP Version 2.4.184 CurlClient is used by defualt for HTTP requests. During CurlClient instance creation, the `defaultOptions` fieldis also initialized #[CurlClient:63](https://github.com/MISP/MISP/blob/88f83ea295a7720037725ec415af0eb1e093fbf8/app/Lib/Tools/CurlClient.php#L63). This initialization also defines the default (empty) proxy option. In the progress, in for example in Sync-Tool, the proxy is set after the instantiation of the CurlClient, but as the `defaultOption` filed is only initialized during object creation and doesn't get updated, the proxy setting doesn't apply. 

### Expected behavior

The Proxy setting should apply after CurlClient object creation.

### Steps to reproduce

Try any sync process, a connection test to a remote server or open the Server Settings & Maintenance -> Diagnostic Page, on a MISP instance without direct internet access and configured Proxy.
You would get a Connection Timeout:

```
[SocketException] curl error 28 'Timeout was reached': Connection timed out after 30000 milliseconds
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(85): CurlClient->internalRequest()
#1 /var/www/MISP/app/Lib/Tools/GitTool.php(43): CurlClient->get()
#2 /var/www/MISP/app/Lib/Tools/GitTool.php(27): GitTool::gitHubRequest()
#3 /var/www/MISP/app/Model/Server.php(4194): GitTool::getLatestCommit()
#4 /var/www/MISP/app/Controller/ServersController.php(1136): Server->getCurrentGitStatus()
#5 [internal function]: ServersController->serverSettings()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
```

### Version

2.4.184

### Operating System

Centos

### Operating System version

8

### PHP version

7.4.30

### Relevant log output

```shell
[SocketException] curl error 28 'Timeout was reached': Connection timed out after 30000 milliseconds
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(85): CurlClient->internalRequest()
#1 /var/www/MISP/app/Lib/Tools/GitTool.php(43): CurlClient->get()
#2 /var/www/MISP/app/Lib/Tools/GitTool.php(27): GitTool::gitHubRequest()
#3 /var/www/MISP/app/Model/Server.php(4194): GitTool::getLatestCommit()
#4 /var/www/MISP/app/Controller/ServersController.php(1136): Server->getCurrentGitStatus()
#5 [internal function]: ServersController->serverSettings()
#6 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Controller/Controller.php(499): ReflectionMethod->invokeArgs()
#7 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction()
#8 /var/www/MISP/app/Vendor/cakephp/cakephp/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke()
#9 /var/www/MISP/app/webroot/index.php(101): Dispatcher->dispatch()
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Felix83000** [comment]
Hi,

We have the same issue here in 2.4.184

In which version the fix will be applied? 

Thanks

**Comment by Kagee** [comment]
The fix is pushed to 2.4, it will become 2.4.185 when published.

**Comment by ForMaMi** [comment]
Sorry, I still can't synchronize with another server. When will the bug be fixed?

**Comment by Kagee** [comment]
The bug as described here was fixed in 2.4.185, and has been fixed in the two latest releases. If you still have problems, make sure you have restarted your workers after upgrading. If the issue persists, open a new issue with logs.

**Comment by ForMaMi** [comment]
Hi, I upgraded to MISP version 2.4.187 but I still get this error during a sync: 
2024-03-11 02:01:32 Error: Could not fetch event IDs from server `XXXX`.
[SocketException] curl error 28 'Timeout was reached': Operation timed out after 90000 milliseconds with 87408640 out of 281464902 bytes received
Stack Trace:
#0 /var/www/MISP/app/Lib/Tools/CurlClient.php(92): CurlClient->internalRequest()
#1 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(570): CurlClient->post()
#2 /var/www/MISP/app/Lib/Tools/ServerSyncTool.php(84): ServerSyncTool->post()
#3 /var/www/MISP/app/Model/Server.php(915): ServerSyncTool->eventIndex()
#4 /var/www/MISP/app/Model/Server.php(1014): Server->getEventIndexFromServer()
#5 /var/www/MISP/app/Model/Server.php(279): Server->getEventIdsFromServer()
#6 /var/www/MISP/app/Model/Server.php(642): Server->__getEventIdListBasedOnPullTechnique()
#7 /var/www/MISP/app/Console/Command/ServerShell.php(149): Server->pull()
#8 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/Shell.php(459): ServerShell->pull()
#9 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(222): Shell->runCommand()
#10 /var/www/MISP/app/Lib/cakephp/lib/Cake/Console/ShellDispatcher.php(66): ShellDispatcher->dispatch()
#11 /var/www/MISP/app/Console/cake.php(45): ShellDispatcher::run()
#12 {main}
ERROR: curl error 28 'Timeout was reached': Operation timed out after 90000 milliseconds with 87408640 out of 281464902 bytes received

**Comment by Kagee** [comment]
Please make sure you have restarted your workers after upgrading.

**Comment by Benni0** [comment]
@ForMaMi
that's another issue which is not related to this one.
Your connection times out after 90 second timeout and receiving ~87MB of data.
This means that the connection was established, but a 90 second timeout dropped it.
If the connection wouldn't work, there would also no data be transferred.

**Comment by ForMaMi** [comment]
I have already restarted the workers. I made these changes: 
vi /var/www/MISP/app/Lib/Tools/CurlClient.php
#private $timeout = 30;
private $timeout = 90;
systemctl restart apache2.service
sudo su -l www-data -s /bin/bash "/var/www/MISP/app/Console/worker/start.sh"

**Comment by ForMaMi** [comment]
Thursday 7th I made this change and managed to synchronize the events, now it times out again

**Comment by Benni0** [comment]
That is the reason for the timeout of 90 seconds, but you have to figure out, why this timeout appears.
Your issue is related to your environment and not to MISP Software.
I would recommend to generate some TCP dumps on both instances and try to debug your connection issue. A proxy in between can alse cause this problem.
Also review the logs of both MISP instances, maybe there is a hint, why the other instance stops sending.

To make it clear again, your problem has nothing to do with the issue described here.

**Comment by Kagee** [comment]
@ForMaMi Please, if you want to follow this up, make an issue of your own. However, if i read the logs correctly it sounds like your MISP is only able to download at speeds of 1 MB/s / 8 Mbps. This is much lower than MISP is expected and this designed to operate. This does not appear to be a MISP problem, but with you network/internet access.

**Comment by ForMaMi** [comment]
Perfect, I will try to follow your advice. I will keep you up to date

**Comment by ForMaMi** [comment]
To get my synchronization working I went back to release 2.4.183.

**Comment by Kagee** [comment]
ForMaMi: Please create another issue. Reverting to 2.5.183 is not a solution. You need to find out why your misp can only download at 8Mpbs.
